<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Localization\Test\LocalizationBootstrap'          => __DIR__ . '/test/Bootstrap.php',
    'Localization\Test\Model\LocalizationBaseTest'     => __DIR__ . '/test/Localization/src/Localization/Model/LocalizationBaseTest.php',
    'Localization\Test\Service\LocalizationLocaleTest' => __DIR__ . '/test/Localization/src/Localization/Utility/LocalizationLocaleTest.php',
    'Localization\Module'                              => __DIR__ . '/Module.php',
    'Localization\Controller\Plugin\Localization'      => __DIR__ . '/src/Localization/Controller/Plugin/Localization.php',
    'Localization\View\Helper\Localization'            => __DIR__ . '/src/Localization/View/Helper/Localization.php',
    'Localization\Exception\LocalizationException'     => __DIR__ . '/src/Localization/Exception/LocalizationException.php',
    'Localization\Event\LocalizationEvent'             => __DIR__ . '/src/Localization/Event/LocalizationEvent.php',
    'Localization\Service\Localization'                => __DIR__ . '/src/Localization/Service/Localization.php',
    'Localization\Model\LocalizationBase'              => __DIR__ . '/src/Localization/Model/LocalizationBase.php',
    'Localization\Model\LocalizationAdministration'    => __DIR__ . '/src/Localization/Model/LocalizationAdministration.php',
    'Localization\Utility\LocalizationCache'           => __DIR__ . '/src/Localization/Utility/LocalizationCache.php',
    'Localization\Utility\LocalizationLocale'          => __DIR__ . '/src/Localization/Utility/LocalizationLocale.php',
    'Localization\XmlRpc\LocalizationHandler'          => __DIR__ . '/src/Localization/XmlRpc/LocalizationHandler.php',
);
