<?php $this->declareVars('extraActions', 'pagesTreeId') ?>

<?php $this->pagesTreeId = 'pages-tree' ?>
<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'pages-administration',
        'action' => 'edit-page',
        'params' => [
            'slug' => $this->page_info['id']
        ],
        'name' => $this->translate('Edit the page'),
        'check_acl' => true
    ],
    [
        'hide_action' => $this->page_info['right_key'] - $this->page_info['left_key'] != 1 || $this->page_info['dependent_page'],
        'controller' => 'pages-administration',
        'action' => 'delete-pages',
        'name' => $this->translate('Delete the page'),
        'check_acl' => true,
        'confirm' => $this->translate('Page will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'pages' : [{$this->page_info['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'pages-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'system-pages',
        'name' => $this->translate('Add system pages'),
        'query' => [
            'page_id' => $this->page_info['id']
        ],
        'check_acl' => true
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'add-custom-page',
        'name' => $this->translate('Add a custom page'),
        'query' => [
            'page_id' => $this->page_info['id']
        ],
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <div class="col-md-4">
        <?php if (false !== $this->aclCheckPermission('pages_administration_ajax_add_widget')): ?>
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Widgets'),
                'body' => $this->partial('page/administration-partial/_add-widgets', [
                    'page_info' => $this->page_info,
                    'paginator' => $this->paginator,
                    'per_page' => $this->per_page,
                    'filter_form' => $this->filter_form,
                    'filters' => $filters
                ])
            ]) ?>
        <?php endif ?>

        <?php if ($this->extraActions): ?>
            <?php echo $this->extraActions ?>
        <?php endif ?>

        <?php echo $this->partial('administration-partial/panel', [
            'notification' => false,
            'title' => $this->translate('Viewing widgets'),
            'body' => $this->pageTree($this->pagesTreeId, $this->page_info['id'], false, [], false, true)
        ]) ?>
    </div>
    <div class="col-md-8">
        <?php echo $this->partial('page/administration-partial/_manage-widgets-wrapper', [
            'layouts' => $this->layouts,
            'page_info' => $this->page_info,
            'manage_layout' => $this->manage_layout,
            'widgets_connections' => $this->widgets_connections
        ]) ?>
    </div>
</div>

<script type="text/javascript">
    var pageWidget = new Widget({
        'widgetsWrapper' : 'widgets-wrapper',
        'widgetsRefreshUrl' : '<?php echo $this->url('application/page', [
                'controller' => 'pages-administration',
                'action' => 'browse-widgets',
                'per_page' => $this->per_page,
                'page' => $this->page,
                'slug' => $this->page_info['id']], ['force_canonical' => true, 'query' => $filters]) ?>'
    });

    <?php if ($this->aclCheckPermission('pages_administration_ajax_change_widget_position')): ?>
        <!-- init sortable -->
        $('ul.connected-sortable').sortable({
            'connectWith' : 'ul.connected-sortable',
            'placeholder' : 'ui-state-highlight',
            'handle' : '.sortable-handler',
            'stop' : function (e, ui) {

                params = {
                    'widget_order' : $(ui.item).index(),
                    'widget_connection'  : $(ui.item).attr('widget-connection'),
                    'widget_position' : $(ui.item).parent().attr('position')
                };

                // save a selected widget's position
                pageWidget.getPage('<?php echo $this->url('application/page', ['controller' => 'pages-administration', 'action' => 'ajax-change-widget-position'], ['force_canonical' => true]) ?>', params);
            }
        }).disableSelection();
    <?php endif ?>

    <!-- init widgets actions tooltips -->
    $('div#widgets-wrapper div.widget-actions .tooltip-handler').tooltip({
        'placement' : <?php if ($this->localization()->isCurrentLanguageLtr()) : ?>'right'<?php else: ?>'left'<?php endif ?>,
        'html' : true
    });

    <!-- init confirm -->
    $('div#widgets-wrapper div.widget-actions .confirm-handler').bind('click', function(e){
        e.preventDefault();
        e.stopPropagation();
        var $link = $(this);

        showConfirmPopup('<?php echo $this->escapeJs($this->translate('Yes')) ?>', '<?php echo $this->escapeJs($this->translate('No')) ?>', this, function (){
            pageWidget.getPage($link.attr('href'));
        })
    });
</script>