<?php $this->declareVars('subPageTitle', 'mainPageTitle', 'extraActions') ?>

<?php $this->subPageTitle  = $this->translate('Add a file') ?>
<?php $this->mainPageTitle = $this->translate('List of files') ?>

<?php $this->headTitle($this->subPageTitle)  ?>
<?php $this->headTitle($this->mainPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('file-manager/file-manager-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->mainPageTitle,
            'controller' => 'files-manager-administration',
            'action' => 'list',
            'check_acl' => true,
            'queries' => [
                'path' => $this->path
            ]
        ],
        'add_directory' => [
            'name' => $this->subPageTitle,
            'controller' => 'files-manager-administration',
            'action' => 'add-file',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->placeholder('form')->captureStart() ?>
    <?php if ($this->file_form) : ?>
        <?php echo $this->partial('file-manager/partial/file-form', [
            'form' => $this->file_form
        ]) ?>
    <?php else: ?>
        <div class="alert alert-danger">
            <?php echo $this->translate('Directory not exists') ?>
        </div>
    <?php endif; ?>
<?php $this->placeholder('form')->captureEnd() ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'files-manager-administration',
        'action' => 'add-directory',
        'query' => [
            'path' => $this->path
        ],
        'name' => $this->translate('Add a directory'),
        'check_acl' => true
    ]]
]))
?>

<?php echo $this->partial('file-manager/partial/file-manager-wrapper', [
    'user_directories' => $this->user_directories,
    'action' => $this->placeholder('form'),
    'action_title' => $this->translate('General info'),
    'path' => $this->path,
    'filters' => [],
    'extra_actions' => $this->extraActions,
    'link_description' => $this->translate('Make this directory as a parent of current file')
]) ?>