<?php $this->declareVars('subPageTitle', 'mainPageTitle', 'content') ?>

<?php $this->subPageTitle  = $this->translate('Add a directory') ?>
<?php $this->mainPageTitle = $this->translate('List of files') ?>

<?php $this->headTitle($this->subPageTitle)  ?>
<?php $this->headTitle($this->mainPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('file-manager/file-manager-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->mainPageTitle,
            'controller' => 'files-manager-administration',
            'action' => 'list',
            'check_acl' => true,
            'queries' => [
                'path' => $this->path
            ]
        ],
        'add_directory' => [
            'name' => $this->subPageTitle,
            'controller' => 'files-manager-administration',
            'action' => 'add-directory',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->placeholder('form')->captureStart() ?>
    <?php if ($this->directoryForm) : ?>
        <?php echo $this->partial('file-manager/patrial/directory-form', [
            'form' => $this->directoryForm,
        ]) ?>
    <?php else: ?>
        <div class="alert alert-danger">
            <?php echo $this->translate('Directory not exists') ?>
        </div>
    <?php endif; ?>
<?php $this->placeholder('form')->captureEnd() ?>

<?php $this->content = $this->partial('file-manager/patrial/tree', [
    'userDirectories' => $this->userDirectories,
    'action' => $this->placeholder('form'),
    'path' => $this->path,
    'filters' => []
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Directory'),
    'body' => $this->content
]) ?>