<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of files') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('file-manager/file-manager-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<?php $this->placeholder('filesList')->captureStart() ?>
    <?php echo $this->partial('file-manager/patrial/files-list', [
        'current_directory' => $this->current_directory,
        'paginator' => $this->paginator,
        'path' => $this->path,
        'order_by' => $this->order_by,
        'order_type' => $this->order_type,
        'per_page' => $this->per_page,
        'filter_form' => $this->filter_form,
        'filters' => $this->filters
    ]) ?>
<?php $this->placeholder('filesList')->captureEnd() ?>

<?php echo $this->partial('file-manager/patrial/tree', [
    'userDirectories' => $this->userDirectories,
    'action' => $this->placeholder('filesList'),
    'path' => $this->path,
    'filters' => $this->filters
]) ?>

