<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('List of files') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('file-manager/file-manager-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->subPageTitle,
            'controller' => 'files-manager-administration',
            'action' => 'list',
            'check_acl' => true
        )
    )
)) ?>

<?php $this->placeholder('filesList')->captureStart() ?>
    <?php echo $this->partial('file-manager/patrial/files_list', array(
        'paginator' => $this->paginator,
        'path' => $this->path,
        'order_by' => $this->order_by,
        'order_type' => $this->order_type,
        'per_page' => $this->per_page,
        'filter_form' => $this->filter_form,
        'filters' => $this->filters
    )); ?>
<?php $this->placeholder('filesList')->captureEnd() ?>

<?php echo $this->partial('file-manager/patrial/tree', array(
    'userDirectories' => $this->userDirectories,
    'action' => $this->placeholder('filesList'),
    'path' => $this->path,
    'filters' => $this->filters
)); ?>