<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Layout\Test\LayoutBootstrap'                => __DIR__ . '/test/Bootstrap.php',
    'Layout\Test\View\Helper\LayoutHeadLinkTest' => __DIR__ . '/test/Layout/src/Layout/View/Helper/LayoutHeadLinkTest.php',
    'Layout\Module'                              => __DIR__ . '/Module.php',
    'Layout\View\Resolver\TemplatePathStack'     => __DIR__ . '/src/Layout/View/Resolver/TemplatePathStack.php',
    'Layout\View\Helper\LayoutAsset'             => __DIR__ . '/src/Layout/View/Helper/LayoutAsset.php',
    'Layout\View\Helper\LayoutHeadLink'          => __DIR__ . '/src/Layout/View/Helper/LayoutHeadLink.php',
    'Layout\View\Helper\LayoutHeadScript'        => __DIR__ . '/src/Layout/View/Helper/LayoutHeadScript.php',
    'Layout\View\Helper\LayoutHeadResource'      => __DIR__ . '/src/Layout/View/Helper/LayoutHeadResource.php',
    'Layout\Exception\LayoutException'           => __DIR__ . '/src/Layout/Exception/LayoutException.php',
    'Layout\Event\LayoutEvent'                   => __DIR__ . '/src/Layout/Event/LayoutEvent.php',
    'Layout\Service\Layout'                      => __DIR__ . '/src/Layout/Service/Layout.php',
    'Layout\Model\LayoutBase'                    => __DIR__ . '/src/Layout/Model/LayoutBase.php',
    'Layout\Model\LayoutAdministration'          => __DIR__ . '/src/Layout/Model/LayoutAdministration.php',
    'Layout\Utility\LayoutCache'                 => __DIR__ . '/src/Layout/Utility/LayoutCache.php',
];
