<!-- include needed js and css files -->
<?php $this->layoutHeadScript()->appendFile($this->layoutAsset('widget.js', 'js', 'page')) ?>
<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('administration.css', 'css', 'page')) ?>

<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Browse widgets') ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->pageTitle($this->page_info)) ?>
<?php $this->headTitle($this->translate('List of pages')) ?>

<!-- render a header -->
<?php echo $this->render('page/page-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of pages'),
            'controller' => 'pages-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_widgets' => [
            'name' => $this->pageTitle($this->page_info) . ' - ' . $this->subPageTitle,
            'controller' => 'pages-administration',
            'action' => 'browse-widgets',
            'check_acl' => true
        ]
    ]
]) ?>

<div id="widgets-wrapper">
    <?php echo $this->partial('page/administration-partial/browse-widgets-wrapper', [
        'csrf_token' => $this->csrf_token,
        'page' => $this->page,
        'page_info' => $this->page_info,
        'paginator' => $this->paginator,
        'per_page' => $this->per_page,
        'filter_form' => $this->filter_form,
        'filters' => $this->filters,
        'layouts' => $this->layouts,
        'manage_layout' => $this->manage_layout,
        'widgets_connections' => $this->widgets_connections
    ]) ?>
</div>