<?php $this->declareVars('extraActions', 'subPageTitle', 'parentPageTitle', 'settingsTitle', 'listPagesTitle') ?>
<?php $this->subPageTitle =  $this->pageWidgetTitle($this->widget_info) ?>
<?php $this->parentPageTitle = $this->translate('Browse widgets') ?>
<?php $this->settingsTitle = $this->translate('Settings') ?>
<?php $this->listPagesTitle = $this->translate('List of pages') ?>

<?php $this->headTitle($this->settingsTitle) ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>
<?php $this->headTitle($this->pageTitle($this->page_info)) ?>
<?php $this->headTitle($this->listPagesTitle) ?>

<!-- render a header -->
<?php echo $this->render('page/page-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->listPagesTitle,
            'controller' => 'pages-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_widgets' => [
            'name' => $this->pageTitle($this->page_info) . ' - ' . $this->parentPageTitle,
            'controller' => 'pages-administration',
            'action' => 'browse-widgets',
            'check_acl' => true,
            'params' => [
                'slug' => $this->page_info['id']
            ]
        ],
        'widget_settings' => [
            'name' =>  $this->subPageTitle . ' - ' . $this->settingsTitle,
            'controller' => 'pages-administration',
            'action' => 'widget-settings',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'hide_action' => $this->widget_info['widget_depend_connection_id'] || $this->widget_info['widget_page_depend_connection_id'],
        'controller' => 'pages-administration',
        'action' => 'ajax-delete-widget',
        'params' => [
            'slug' => $this->widget_info['id']
        ],
        'query' => [
            'csrf' => $this->csrf_token
        ],
        'name' => $this->translate('Delete widget'),
        'check_acl' => true,
        'confirm' => $this->translate('Widget will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), function(){location.href='{$this->url('application/page', ['controller' => 'pages-administration', 'action' => 'browse-widgets', 'slug' => $this->page_info['id']], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'edit-page',
        'params' => [
            'slug' => $this->page_info['id']
        ],
        'name' => $this->translate('Edit the page'),
        'check_acl' => true
    ],
    [
        'hide_action' => $this->page_info['right_key'] - $this->page_info['left_key'] != 1 || $this->page_info['dependent_page'],
        'controller' => 'pages-administration',
        'action' => 'delete-pages',
        'name' => $this->translate('Delete the page'),
        'check_acl' => true,
        'confirm' => $this->translate('Page will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'pages' : [{$this->page_info['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'pages-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'system-pages',
        'name' => $this->translate('Add system pages'),
        'query' => [
            'page_id' => $this->page_info['id']
        ],
        'check_acl' => true
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'add-custom-page',
        'name' => $this->translate('Add a custom page'),
        'query' => [
            'page_id' => $this->page_info['id']
        ],
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Settings'),
                'body' => $this->partial('partial/form', ['form' => $this->settings_form])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Settings'),
                'body' => $this->partial('partial/form', ['form' => $this->settings_form])
            ]) ?>
        </div>
    <?php endif ?>
</div>