<?php $this->declareVars('extraActions', 'subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Edit the page') ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->pageTitle($this->page)) ?>
<?php $this->headTitle($this->translate('List of pages')) ?>

<!-- render a header -->
<?php echo $this->render('page/page-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of pages'),
            'controller' => 'pages-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'edit_page' => [
            'name' => $this->pageTitle($this->page) . ' - ' . $this->subPageTitle,
            'controller' => 'pages-administration',
            'action' => 'edit-page',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'pages-administration',
        'action' => 'browse-widgets',
        'params' => [
            'slug' => $this->page['id']
        ],
        'name' => $this->translate('Browse widgets'),
        'check_acl' => true
    ],
    [
        'hide_action' => $this->page['right_key'] - $this->page['left_key'] != 1 || $this->page['dependent_page'],
        'controller' => 'pages-administration',
        'action' => 'delete-pages',
        'name' => $this->translate('Delete the page'),
        'check_acl' => true,
        'confirm' => $this->translate('Page will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'pages' : [{$this->page['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'pages-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'system-pages',
        'name' => $this->translate('Add system pages'),
        'query' => [
            'page_id' => $this->page['id']
        ],
        'check_acl' => true
    ],
    [
        'controller' => 'pages-administration',
        'action' => 'add-custom-page',
        'name' => $this->translate('Add a custom page'),
        'query' => [
            'page_id' => $this->page['id']
        ],
        'check_acl' => true
    ]]
]))
?>

<?php echo $this->partial('page/administration-partial/page-wrapper', [
    'filters' => [],
    'add_root' => false,
    'tree_disabled' => $this->tree_disabled,
    'page_id' => $this->page_id,
    'action' => $this->partial('partial/form', ['form' => $this->page_form]),
    'action_title' => $this->translate('Edit the page'),
    'extra_actions' => $this->extraActions,
    'link_description' => $this->translate('Make this page as a parent of current page')
]) ?>