<?php $this->declareVars('subPageTitle', 'parentPageTitle', 'settingsTitle', 'listPagesTitle') ?>
<?php $this->subPageTitle =  $this->pageWidgetTitle($this->widget_info) ?>
<?php $this->parentPageTitle = $this->translate('Browse widgets') ?>
<?php $this->settingsTitle = $this->translate('Settings') ?>
<?php $this->listPagesTitle = $this->translate('List of pages') ?>

<?php $this->headTitle($this->settingsTitle) ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>
<?php $this->headTitle($this->pageTitle($this->page_info)) ?>
<?php $this->headTitle($this->listPagesTitle) ?>

<!-- render a header -->
<?php echo $this->render('page/page-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->listPagesTitle,
            'controller' => 'pages-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_widgets' => [
            'name' => $this->pageTitle($this->page_info) . ' - ' . $this->parentPageTitle,
            'controller' => 'pages-administration',
            'action' => 'browse-widgets',
            'check_acl' => true,
            'params' => [
                'slug' => $this->page_info['id']
            ]
        ],
        'widget_settings' => [
            'name' =>  $this->subPageTitle . ' - ' . $this->settingsTitle,
            'controller' => 'pages-administration',
            'action' => 'widget-settings',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Settings'),
    'body' => $this->partial('partial/form', ['form' => $this->settings_form])
]) ?>