<!-- include needed js and css files -->
<?php $this->layoutHeadScript()->appendFile($this->layoutAsset('widget.js', 'js', 'page')) ?>
<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('administration.css', 'css', 'page')) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'edit_page' => [
            'name' => $this->pageTitle($this->page_info) . ' - ' . $this->translate('Edit the page'),
            'controller' => 'pages-administration',
            'action' => 'edit-page',
            'check_acl' => true,
            'params' => [
                'slug' => $this->page_info['id']
            ],
            'queries' => [
                'embed_mode' => true
            ]
        ],
        'browse_widgets' => [
            'name' => $this->translate('Browse widgets'),
            'controller' => 'pages-administration',
            'action' => 'browse-widgets',
            'check_acl' => true
        ]
    ]
]) ?>

<div id="widgets-wrapper">
    <?php echo $this->partial('page/administration-partial/embed-browse-widgets-wrapper', [
        'csrf_token' => $this->csrf_token,
        'page' => $this->page,
        'page_info' => $this->page_info,
        'paginator' => $this->paginator,
        'per_page' => $this->per_page,
        'filter_form' => $this->filter_form,
        'filters' => $this->filters,
        'layouts' => $this->layouts,
        'manage_layout' => $this->manage_layout,
        'widgets_connections' => $this->widgets_connections
    ]) ?>
</div>