<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of pages') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('page/page-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'pages-administration',
    'action' => 'list',
    'queries' => [
        'page_id' => $this->page_id
    ],
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'position',
    'default_order_type' => 'asc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('Position'),
            'order_name' => 'position'
        ],
        [
            'title' => $this->translate('Title')
        ],
        [
            'title' => $this->translate('Display name'),
            'order_name' => 'slug'
        ],
        [
            'title' => $this->translate('Widgets'),
            'order_name' => 'widgets'
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'type',
        'system_title',
        'left_key',
        'right_key',
        'dependent_page',
        'system_page'
    ],
    'helpers' => [
        'position' => 'pagePosition',
        'title' => 'pageTitle',
        'active' => 'applicationBooleanValue'
    ],
    'helpers_options' => [
        'position' => [
            'page_number' => $paginator->getCurrentPageNumber(),
            'per_page' => $paginator->getItemCountPerPage(),
            'items_count' => $paginator->getTotalItemCount(),
            'order_type' => $this->order_type
        ]
    ],
    'helpers_set_array' => [
        'title' => true
    ],
    'actions' => [
        'regular_actions' => [
            [
                'name' => $this->translate('Add system pages'),
                'controller' => 'pages-administration',
                'action' => 'system-pages',
                'check_acl' => true,
                'queries' => [
                    'page_id' => $this->page_id
                ]
            ],
            [
                'name' => $this->translate('Add a custom page'),
                'controller' => 'pages-administration',
                'action' => 'add-custom-page',
                'check_acl' => true,
                'queries' => [
                    'page_id' => $this->page_id
                ]
            ],
        ],
        'multiple_actions' => [
            [
                'name' => $this->translate('Delete selected'),
                'controller' => 'pages-administration',
                'action' => 'delete-pages',
                'check_acl' => true,
                'confirm' => $this->translate('Selected pages will be deleted. Are you sure?')
            ]
        ],
        'single_actions' => [
            [
                'name' => $this->translate('View dependent pages'),
                'js' => 'showPopup(\'' . $this->url('application/page', ['controller' => 'pages-administration', 'action' => 'ajax-view-dependent-pages']) . '?page_id=__value__\', \'popup-page-depends-window\')',
                'check_acl' => true,
                'param' => 'system_page',
                'controller' => 'pages-administration',
                'action' => 'ajax-view-dependent-pages',
                'image' => $this->layoutAsset('icon/depend_action.png', 'image', 'page')
            ],
            [
                'name' => $this->translate('Edit the page'),
                'controller' => 'pages-administration',
                'action' => 'edit-page',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/edit_action.png', 'image')
            ],
            [
                'name' => $this->translate('Browse widgets'),
                'controller' => 'pages-administration',
                'action' => 'browse-widgets',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/widget_action.png', 'image', 'page')
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'pages',
        'multiple_actions' => [
            'items_name' => 'pages[]'
        ]
    ],
    'actions_extra_check' => [
        'regular_actions' => [
            'add-custom-page' => [
                function() use ($pages_map) {
                    return count($pages_map)  > 0;
                }
            ]
        ],
        'multiple_actions' => [
            'deletable' => [
                'function' => function($data) {
                    // check subpages
                    if ($data['right_key'] - $data['left_key'] == 1) {
                        // check page depends
                        if (!$data['dependent_page']) {
                            return true;
                        }
                    }

                    return false;
                }
            ]
        ],
        'multiple_actions_message' => $this->translate('You have to delete subpages or dependent pages before you can delete this page'),
        'single_actions' => [
            'ajax-view-dependent-pages' => [
                [
                    'param' => 'dependent_page',
                    'condition' =>  'return (int) "__value__" ? true : false;'
                ]
            ]
        ]
    ]
]) ?>

<?php echo $this->partial('page/administration-partial/page-wrapper', [
    'filters' => $this->filters,
    'add_root' => true,
    'page_id' => $this->page_id,
    'action' => $this->content,
    'action_title' => $this->translate('Pages'),
    'link_description' => $this->translate('View subpages')
]) ?>
