<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('System pages')  ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('List of pages')) ?>

<!-- render a header -->
<?php echo $this->render('page/page-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of pages'),
            'controller' => 'pages-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'system_pages' => [
            'name' => $this->subPageTitle,
            'controller' => 'pages-administration',
            'action' => 'system-pages',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'pages-administration',
    'action' => 'system-pages',
    'queries' => [
        'page_id' => $this->page_id
    ],
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'asc',
    'filter_form' => $this->filter_form,
    'headers' => [
        0 => [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        1 => [
            'title' => $this->translate('Title')
        ],
        2 => [
            'title' => $this->translate('Display name'),
            'order_name' => 'slug'
        ],
        3 => [
            'title' => $this->translate('Module')
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'dependent_page',
        'structure_slug'
    ],
    'helpers' => [
        'module_name' => 'translate',
        'title' => 'translate'
    ],
    'helpers_options' => [
    ],
    'helpers_set_array' => [
    ],
    'actions' => [
        'regular_actions' => [
        ],
        'multiple_actions' => [
            0 => [
                'name' => $this->translate('Add selected'),
                'controller' => 'pages-administration',
                'action' => 'add-system-pages',
                'check_acl' => true,
                'confirm' => $this->translate('Selected pages will be added to the pages tree with all their dependencies. Are you sure?'),
                'queries' => [
                    'page_id' => $this->page_id
                ]
            ]
        ],
        'single_actions' => [
            0 => [
                'name' => $this->translate('View dependent pages'),
                'js' => 'showPopup(\'' . $this->url('application/page', ['controller' => 'pages-administration', 'action' => 'ajax-view-dependent-pages']) . '?check_structure=-1&page_id=__value__\', \'popup-page-depends-window\')',
                'check_acl' => true,
                'controller' => 'pages-administration',
                'action' => 'ajax-view-dependent-pages',
                'image' => $this->layoutAsset('icon/depend_action.png', 'image', 'page')
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'pages',
        'multiple_actions' => [
            'items_name' => 'pages[]'
        ]
    ],
    'actions_extra_check' => [
        'multiple_actions' => [
            'already_used' => [
                'param' => 'structure_slug',
                'condition' =>  'return "" == "__value__" ? true : false;'
            ]
        ],
        'multiple_actions_message' => $this->translate('A custom page already created with this page display name. Please remove or rename the custom page before you can add this page.'),
        'single_actions' => [
            'ajax-view-dependent-pages' => [
                0 => [
                    'param' => 'dependent_page',
                    'condition' =>  'return (int) "__value__" ? true : false;'
                ]
            ]
        ]
    ]
]) ?>

<?php echo $this->partial('page/administration-partial/page-wrapper', [
    'filters' => [],
    'add_root' => false,
    'page_id' => $this->page_id,
    'action' => $this->content,
    'action_title' => $this->subPageTitle,
    'pagesTreeTitle' =>  $this->translate('Root of pages')
]) ?>