<ol class="breadcrumb">
    <li>
        <a href="<?php echo $this->url('page', [], ['force_canonical' => true]) ?>">
            <?php echo $this->translate('Home') ?>
        </a>
    </li>
    <?php foreach($this->breadcrumb as $page) : ?>
        <li>
            <?php if (!$page['url']) : ?>
                <?php echo $page['title'] ?>
            <?php else: ?>
                <a href="<?php echo $this->url('page', ['page_name' => $page['url']], ['force_canonical' => true]) ?>">
                    <?php echo $page['title'] ?>
                </a>
            <?php endif ?>
        </li>
    <?php endforeach ?>
</ol>