<!-- include needed js and css files -->
<?php $this->layoutHeadScript()->appendFile($this->layoutAsset('jquery.treeview.js')) ?>
<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset(($this->localization()->isCurrentLanguageLtr()
        ? 'jquery.treeview.css'
        : 'jquery.treeview.rtl.css'), 'css')) ?>

<div id="pages-tree-wrapper" class="tree-wrapper">
    <ul id="<?php echo $this->escapeHtmlAttr($this->tree_id) ?>">
        <?php echo $this->tree ?>
    </ul>
</div>

<script type="text/javascript">
        $("#<?php echo $this->escapeJs($this->tree_id) ?>").treeview({
            persist: "cookie",
            cookieOptions : {
                expires: <?php echo $this->cookie_lifetime ?>,
                path : '<?php echo $this->url('application/page', ['controller' => $this->applicationRoute()->getParam('controller')]) ?>'
            }
        });
</script>
