<?php if (count($this->items) > 1): ?>
    <?php $this->declareVars('uncategorized', 'content', 'index') ?>
    <?php $this->uncategorized = null ?>
    <div class="accordion" id="<?php echo $this->name ?>">
        <?php foreach ($this->items as $category => $content) : ?>
            <?php if (null == $category): ?>
                <?php $this->uncategorized .= $content; continue; ?>
            <?php endif; ?>
            <?php $this->index++ ?>
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#<?php echo $this->escapeHtmlAttr($this->name) ?>" href="#collapse-<?php echo $this->index ?>"><?php echo $this->translate($category) ?></a>
                </div>
                <div id="collapse-<?php echo $this->index ?>" class="accordion-body collapse <?php if (($this->index == 1 && ! (array) $this->openCategories) || (in_array($category, (array) $this->openCategories))): ?>in<?php else: ?>collapse<?php endif; ?>">
                    <div class="accordion-inner">
                        <?php echo $content ?>
                    </div>
                </div>
            </div>            
        <?php endforeach; ?>
        <?php echo $this->uncategorized; ?>
    </div>
<?php else: ?>
    <?php echo current($this->items) ?>
<?php endif; ?>

