<?php foreach ($this->flashMessages() as $namespace => $messages) : ?>
    <?php if (count($messages)) : ?>
        <?php foreach ($messages as $message) : ?>
        <div class="alert alert-<?php echo ($namespace == 'error' ? 'danger' : $namespace) ?>">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <?php echo $this->escapeHtml($message); ?>
        </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>
