<?php
    $this->declareVars('queries');
 
    if(!isset($this->params)) {
        $this->params = array();
    }

    $this->queries = !empty($this->queries) && is_array($this->queries)
        ?
            (
                !isset($this->queries_encode) || $this->queries_encode === true
                    ? $this->urlParamsEncode($this->queries)
                    : $this->queries
            )
        : array();
?>

<?php if ($this->pageCount > 1): ?>
    <div class="pagination">
        <ul>
            <!-- Previous page link -->
            <li <?php if (!isset($this->previous)): ?>class="disabled"<?php endif; ?>>
                <?php if (isset($this->previous)): ?>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->previous) + $this->params, array('query' => $this->queries)); ?>">&lt;</a>
                <?php else: ?>
                    <span>&lt;</span>
                <?php endif; ?>
            </li>
            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <li <?php if ($page == $this->current): ?>class="active"<?php endif; ?>>
                    <?php if ($page != $this->current): ?>
                        <a href="<?php echo $this->url($this->route, array('page' => $page) + $this->params, array('query' => $this->queries)); ?>">
                            <?php echo $page; ?>
                        </a>
                    <?php else: ?>
                        <span><?php echo $page; ?></span>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
            <!-- Next page link -->
            <li <?php if (!isset($this->next)): ?>class="disabled"<?php endif; ?>>
                <?php if (isset($this->next)): ?>
                    <a href="<?php echo $this->url($this->route, array('page' => $this->next) + $this->params, array('query' => $this->queries)); ?>">&gt;</a>
                <?php else: ?>
                    <span>&gt;</span>
                <?php endif; ?>
            </li>
        </ul>
    </div>
<?php endif; ?>