<ul class="nav nav-tabs">
    <?php $this->declareVars('aclResource') ?>

    <?php foreach ($this->tabs as $tab) : ?>
        <?php if (!empty($tab['check_acl'])): ?>
            <?php
                $this->aclResource = !empty($tab['acl_resource'])
                    ? $tab['acl_resource'] // check tab permission for specific acl resource
                    : $tab['controller'] . '-' . $tab['action']; // check tab permission for specific controller and action

                // check permission
                if (!$this->checkPermission($this->aclResource)) {
                    continue;
                }
            ?>
        <?php endif; ?>

        <li<?php if ($this->currentRoute()->getController() == $tab['controller'] && $this->currentRoute()->getAction() == $tab['action']): ?> class="active"<?php endif; ?>>
            <a href="<?php echo $this->url(null, array('controller' => $tab['controller'], 'action' => $tab['action'])) ?>">
                <?php echo $this->escapeHtml($tab['name']) ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>