<center>
    <div id="rateit" class="rateit bigstar"></div>
</center>

<script type="text/javascript">
    $("#rateit").rateit({
        "readonly" : false, // if we already voted than disabled it
        "resetable": false,
        //"max": 115, // do we need clear track after each settings changes?
        "value": 1, // already voted
        "step": 0.5, // step should be less than max value
        "starwidth": 32, // or 32 for big stars
        "starheight": 32 // or 32 for big stars
    }).bind('rated', function (event, value) {
        alert('You\'ve rated it: ' + value);
        $(this).rateit('value', 4.5);
        $(this).rateit('readonly', true);
    });
</script>

<!-- http://www.radioactivethinking.com/rateit/example/example.htm#ex_a1 -->