<?php use Zend\Form\Element ?>

<?php $this->declareVars('pageTitle', 'subPageTitle') ?>
<?php $this->pageTitle = $this->translate('Shopping cart') ?>
<?php $this->subPageTitle = $this->translate('Buy items') ?>

<?php $this->headTitle($this->escapeHtml($this->subPageTitle)) ?>
<?php $this->headTitle($this->transaction['slug']) ?>
<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'home' => array(
            'name' => $this->translate('Home'),
            'controller' => 'Home',
            'action' => 'index',
            'check_acl' => false
        ),
        'shopping_cart' => array(
            'name' => $this->pageTitle,
            'controller' => 'payments',
            'action' => 'shopping-cart',
            'check_acl' => false
        ),
        'buy' => array(
            'name' => $this->transaction['slug'] . ' - ' . $this->subPageTitle,
            'controller' => 'payments',
            'action' => 'buy',
            'check_acl' => false
        )
    )
)) ?>