<!-- render a header -->
<?php echo $this->render('payment/payment-type/_header') ?>

<!-- render a payment form -->
<?php
    echo $this->partial('payment/payment-type/_payment-form', array(
        'payments' => $this->payments,
        'current_payment' => $this->current_payment,
        'payment_info' => $this->getSetting('payment_cash_description'),
        'amount' => $this->amount,
        'transaction' => $this->transaction,
        'payment_options' => $this->payment_options,
        'payment_url' => $this->payment_url,
    ));
?>