<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of files'),
            'controller' => $this->applicationRoute()->getParam('controller'),
            'action' => 'list',
            'check_acl' => true,
            'queries' => [
                'path' => $this->path
            ]
        ],
        'add_directory' => [
            'name' => $this->translate('Add a file'),
            'controller' => $this->applicationRoute()->getParam('controller'),
            'action' => 'add-file',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->placeholder('form')->captureStart() ?>
    <?php if ($this->file_form) : ?>
        <?php echo $this->partial('file-manager/patrial/file-form', [
            'form' => $this->file_form
        ]) ?>
    <?php else: ?>
        <div class="alert alert-danger">
            <?php echo $this->translate('Directory not exists') ?>
        </div>
    <?php endif; ?>
<?php $this->placeholder('form')->captureEnd() ?>

<?php echo $this->partial('file-manager/patrial/file-manager-wrapper', [
    'user_directories' => $this->user_directories,
    'action' => $this->placeholder('form'),
    'action_title' => $this->translate('General info'),
    'path' => $this->path,
    'filters' => []
]) ?>