<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->translate('List of files'),
            'controller' => $this->currentRoute()->getController(),
            'action' => 'list',
            'check_acl' => true,
            'queries' => array(
                'path' => $this->path
            )
        ),
        'add_directory' => array(
            'name' => $this->translate('Add a directory'),
            'controller' => $this->currentRoute()->getController(),
            'action' => 'add-directory',
            'check_acl' => true
        )
    )
)) ?>

<?php $this->placeholder('form')->captureStart() ?>
    <?php if ($this->directoryForm) : ?>
        <?php echo $this->partial('file-manager/patrial/directory-form', array(
            'form' => $this->directoryForm,
            'queries' => array(
                'path' => $this->path
            )
        )); ?>
    <?php else: ?>
        <div class="alert alert-danger">
            <?php echo $this->translate('Directory not exists') ?>
        </div>
    <?php endif; ?>
<?php $this->placeholder('form')->captureEnd() ?>

<?php echo $this->partial('file-manager/patrial/tree', array(
    'userDirectories' => $this->userDirectories,
    'action' => $this->placeholder('form'),
    'path' => $this->path,
    'filters' => array()
)); ?>