<?php $this->declareVars('extraActions') ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of files'),
            'controller' => $this->applicationRoute()->getParam('controller'),
            'action' => 'list',
            'check_acl' => true,
            'queries' => [
                'path' => $this->path
            ]
        ],
        'edit_directory' => [
            'name' => $this->translate((!$this->is_directory ? 'Edit the file' : 'Edit the directory')),
            'controller' => $this->applicationRoute()->getParam('controller'),
            'action' => 'edit',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->placeholder('form')->captureStart() ?>
    <?php if ($this->edit_form) : ?>
        <?php echo $this->partial('file-manager/partial/file-form', [
            'form' => $this->edit_form
        ]) ?>
    <?php else: ?>
        <div class="alert alert-danger">
            <?php echo $this->translate('Directory or file not exists') ?>
        </div>
    <?php endif ?>
<?php $this->placeholder('form')->captureEnd() ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'files-manager-embedded',
        'action' => 'delete',
        'query' => [
            'path' => $this->path
        ],
        'name' => $this->translate('Delete'),
        'check_acl' => true,
        'confirm' => $this->translate('File or directory will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'files' : ['{$this->file_name}']}, function(){location.href='{$this->url('application/page', ['controller' => 'files-manager-embedded', 'action' => 'list'], ['query' => ['path' => $this->path], 'force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'files-manager-embedded',
        'action' => 'add-file',
        'query' => [
            'path' => $this->path
        ],
        'name' => $this->translate('Add a file'),
        'check_acl' => true
    ],
    [
        'controller' => 'files-manager-embedded',
        'action' => 'add-directory',
        'query' => [
            'path' => $this->path
        ],
        'name' => $this->translate('Add a directory'),
        'check_acl' => true
    ]]
]))
?>

<?php echo $this->partial('file-manager/partial/file-manager-wrapper', [
    'user_directories' => $this->user_directories,
    'action' => $this->placeholder('form'),
    'action_title' => $this->translate('General info'),
    'path' => $this->path,
    'filters' => [
        'file_path' => $this->file_path,
        'slug' => $this->file_name
    ],
    'extra_actions' => $this->extraActions,
    'link_description' => $this->is_directory
        ? $this->translate('Make this directory as a parent of current directory')
        : $this->translate('Make this directory as a parent of current file')
]) ?>