<?php $this->placeholder('filesList')->captureStart() ?>
    <?php echo $this->partial('file-manager/patrial/file-list', [
        'current_directory' => $this->current_directory,
        'paginator' => $this->paginator,
        'path' => $this->path,
        'order_by' => $this->order_by,
        'order_type' => $this->order_type,
        'per_page' => $this->per_page,
        'filter_form' => $this->filter_form,
        'filters' => $this->filters
    ]) ?>
<?php $this->placeholder('filesList')->captureEnd() ?>

<?php echo $this->partial('file-manager/patrial/file-manager-wrapper', [
    'user_directories' => $this->user_directories,
    'action' => $this->placeholder('filesList'),
    'action_title' => $this->translate('Files and directories'),
    'path' => $this->path,
    'filters' => $this->filters
]) ?>

<?php $this->inlineScript()->captureStart() ?>
    $('div#files-manager-wrapper a.file').bind('click', function(e) {
        e.preventDefault();

        // insert selected url to tinyMce
        parent.tinymce.activeEditor.windowManager.getParams().oninsert($(this).attr('href'));
        parent.tinymce.activeEditor.windowManager.close();
    });
<?php $this->inlineScript()->captureEnd() ?>