<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->translate('List of files'),
            'controller' => $this->currentRoute()->getController(),
            'action' => 'list',
            'check_acl' => true
        )
    )
)) ?>

<?php $this->placeholder('filesList')->captureStart() ?>
    <?php echo $this->partial('file-manager/patrial/files-list', array(
        'current_directory' => $this->current_directory,
        'paginator' => $this->paginator,
        'path' => $this->path,
        'order_by' => $this->order_by,
        'order_type' => $this->order_type,
        'per_page' => $this->per_page,
        'filter_form' => $this->filter_form,
        'filters' => $this->filters
    )); ?>
<?php $this->placeholder('filesList')->captureEnd() ?>

<?php echo $this->partial('file-manager/patrial/tree', array(
    'userDirectories' => $this->userDirectories,
    'action' => $this->placeholder('filesList'),
    'path' => $this->path,
    'filters' => $this->filters
)); ?>

<?php $this->inlineScript()->captureStart() ?>
    $('div#files-manager-wrapper div#action-wrapper').find('a.file').bind("click", function(e) {
        e.preventDefault();

        // insert selected url to tinyMce
        top.tinymce.activeEditor.windowManager.getParams().oninsert($(this).attr('href'));
        top.tinymce.activeEditor.windowManager.close();
    });
<?php $this->inlineScript()->captureEnd() ?>