<?php $this->layout()->help_url = '/docs/install/php-settings' ?>

<?php 
    echo $this->partial('partial/check-page', [
        'image' => 'layout/base/application/image/icon/setting.png',
        'header' => 'PHP settings',
        'content' => $this->partial('partial/table', [
            'headers' => [
                'Name',
                'Current status',
                'Desired status',
            ],
            'list' => $this->settings
        ])
    ])
?>