<?php 
    echo $this->partial('partial/check-page', [
        'header' => 'PHP extensions',
        'content' => $this->partial('partial/table', [
            'headers' => [
                'Extension',
                'Current status',
                'Desired status',
            ],
            'list' => $this->extensions,
            'helpers' => [
                'current' => 'translate',
                'desired' => 'translate'
            ]
        ])
    ])
?>