<div class="page-header">
    <h1><?php echo $this->translate('Permissions') ?></h1>
</div>

<?php
    echo $this->partial('partial/table', [
        'headers' => [
            'Path',
            'Current status',
            'Desired status',
        ],
        'list' => $this->resources,
        'helpers' => [
            'current' => 'translate',
            'desired' => 'translate'
        ]
    ])
?>

<hr />
<p class="text-center">
    <a href="<?php echo $this->url('home/page', [], ['force_canonical' => true], true) ?>" class="text-center btn btn-primary " role="button">
        <?php echo $this->translate('Refresh') ?>
    </a>
</p>
