<?php $this->layout()->help_url = '/docs/install/file-permissions' ?>

<?php 
    echo $this->partial('partial/check-page', [
        'image' => 'layout/base/application/image/icon/info.png',
        'header' => 'Permissions',
        'content' => $this->partial('partial/table', [
            'headers' => [
                'Path',
                'Current status',
                'Desired status',
            ],
            'list' => $this->resources,
            'helpers' => [
                'current' => 'translate',
                'desired' => 'translate'
            ]
        ])
    ])
?>