<?php $this->headScript()->appendFile($this->asset('jquery.treeview.js')) ?>
<?php $this->headLink()->appendStylesheet($this->asset('jquery.treeview.css', 'css')) ?>

<?php $this->declareVars('subPageTitle', 'directoriesTreeId') ?>
<?php $this->directoriesTreeId = 'directories-tree' ?>
<?php $this->subPageTitle = $this->translate('List of files') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('file-manager/file-manager-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->subPageTitle,
            'controller' => 'file-manager-administration',
            'action' => 'list',
            'check_acl' => true
        )
    )
)) ?>

<!-- files manager wrapper -->
<div id="files-manager-wrapper">
    <div class="col-md-3" style=" background-color: #F5F5F5;padding:10px;margin-bottom:10px;overflow: hidden">
        <?php echo $this->filesManagerDirectoriesTree($this->userDirectories, $this->directoriesTreeId) ?>
    </div>
    <div class="col-md-9" style=" margin-bottom:10px">
        <?php if ($this->paginator === false) : ?>
            <div class="alert alert-danger">
                <?php echo $this->translate('Directory not exists') ?>
            </div>
        <?php else: ?>
            <!-- render a data grid -->
            <?php echo $this->partial('partial/data_grid', array(
                'controller' => 'files-manager-administration',
                'action' => 'list',
                'queries' => array(
                    'path' => $this->path
                ),
                'order_by' => $this->order_by,
                'order_type' => $this->order_type,
                'per_page' => $this->per_page,
                'default_order' => 'name',
                'default_order_type' => 'desc',
                'filter_form' => $this->filter_form,
                'headers' => array(
                    0 => array(
                        'title' => $this->translate('Name'),
                        'order_name' => 'name'
                    ),
                    1 => array(
                        'title' => $this->translate('File size'),
                        'order_name' => 'size'
                    )
                ),
                'paginator' => $this->paginator,
                'skipped_fields' => array(
                    'is_directory',
                    'extension',
                    'path'
                ),
                'helpers' => array(
                    'size' => 'fileSize',
                    'name' => 'fileUrl'
                ),
                'helpers_options' => array(
                    'name' => array(
                        'path' => $this->path
                    )
                ),
                'actions' => array(
                ),
                'actions_options' => array(
                ),
                'actions_extra_check' => array(
                )
            )) ?>    
        <?php endif; ?>
    </div>
    <div class="clearfix"></div>
</div>

<?php $this->inlineScript()->captureStart() ?>
    $("#<?php echo $this->directoriesTreeId ?>").treeview({
    });
<?php $this->inlineScript()->captureEnd() ?>