<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Access Control List') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<div class="page-header">
  <h1>
    <img src="<?php  echo $this->asset('icon/acl.png', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
    <?php echo $this->escapeHtml($this->pageTitle) ?>
  </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
    $this->baseTabs = array(
        'list' => array(
          'name' => $this->translate('List of roles'),
          'controller' => 'acl-administration',
          'action' => 'list',
          'check_acl' => true
        ) 
    );
?>