<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'Acl\Form\AclResourceFilter'                 => __DIR__ . '/src/Acl/Form/AclResourceFilter.php',
    'Acl\Form\AclResourceSetting'                => __DIR__ . '/src/Acl/Form/AclResourceSetting.php',
    'Acl\Form\AclRole'                           => __DIR__ . '/src/Acl/Form/AclRole.php',
    'Acl\Form\AclRoleFilter'                     => __DIR__ . '/src/Acl/Form/AclRoleFilter.php',
    'Acl\Event\AclEvent'                         => __DIR__ . '/src/Acl/Event/AclEvent.php',
    'Acl\Service\Acl'                            => __DIR__ . '/src/Acl/Service/Acl.php',
    'Acl\Model\AclBase'                          => __DIR__ . '/src/Acl/Model/AclBase.php',
    'Acl\Model\AclAdministration'                => __DIR__ . '/src/Acl/Model/AclAdministration.php',
    'Acl\Controller\Plugin\AclCheckPermission'   => __DIR__ . '/src/Acl/Controller/Plugin/AclCheckPermission.php',
    'Acl\Controller\AclAdministrationController' => __DIR__ . '/src/Acl/Controller/AclAdministrationController.php',
    'Acl\Exception\AclException'                 => __DIR__ . '/src/Acl/Exception/AclException.php',
    'Acl\View\Helper\AclCheckPermission'         => __DIR__ . '/src/Acl/View/Helper/AclCheckPermission.php',
    'Acl\View\Helper\AclRoutePermission'         => __DIR__ . '/src/Acl/View/Helper/AclRoutePermission.php',
    'Acl\Module'                                 => __DIR__ . '/Module.php',
    'Acl\Test\AclBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
    'Acl\Test\Service\ServiceTest'               => __DIR__ . '/test/Acl/src/Acl/Service/AclTest.php',
];
