<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Membership Levels') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<div class="page-header">
  <h1>
    <img src="<?php  echo $this->asset('icon/membership.png', 'image', 'membership') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
    <?php echo $this->escapeHtml($this->pageTitle) ?>
  </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
    $this->baseTabs = array(
        'list' => array(
            'name' => $this->translate('List of membership levels'),
            'controller' => 'memberships-administration',
            'action' => 'list',
            'check_acl' => true
        ),
        'settings' => array(
            'name' => $this->translate('Settings'),
            'controller' => 'memberships-administration',
            'action' => 'settings',
            'check_acl' => true
        )
    );
?>