<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Modules') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<?php
  $this->baseTabs = [
        'list_installed' => [
            'name' => $this->translate('List of installed modules'),
            'controller' => 'modules-administration',
            'action' => 'list-installed',
            'check_acl' => true
        ],
        'list_not_installed' => [
            'name' => $this->translate('List of not installed modules'),
            'controller' => 'modules-administration',
            'action' => 'list-not-installed',
            'check_acl' => true
        ],
        'add_new' => [
            'name' => $this->translate('Add a new module'),
            'controller' => 'modules-administration',
            'action' => 'add-new',
            'check_acl' => true
        ]
    ];
?>

<div class="page-header">
    <h1>
        <img src="<?php echo $this->layoutAsset('icon/module.png', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
        <?php echo $this->escapeHtml($this->pageTitle) ?>
    </h1>
</div>