<?php $this->declareVars('subPageTitle', 'parentPageTitle', 'moduleName', 'extraActions') ?>
<?php $this->parentPageTitle = $this->translate('Not installed modules') ?>
<?php $this->subPageTitle = $this->translate('Delete the module')  ?>
<?php $this->moduleName = $this->translate($this->module_name) ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->moduleName) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('application/application-module-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-not-installed' // selected action is "list-not-installed"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'modules-administration',
            'action' => 'list-not-installed',
            'check_acl' => true
        ],
        'delete_module' => [
            'name' => $this->moduleName . ' - ' . $this->subPageTitle,
            'controller' => 'modules-administration',
            'action' => 'upload',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'modules-administration',
        'action' => 'upload',
        'name' => $this->translate('Upload a module'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
   <?php if (!$this->extraActions): ?> 
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->subPageTitle,
                'body' => $this->partial('partial/form', ['form' => $this->module_form])
            ]) ?>
        </div>
    <?php else: ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->subPageTitle,
                'body' => $this->partial('partial/form', ['form' => $this->module_form])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php endif ?>
</div>
