<?php $this->declareVars('subPageTitle', 'parentPageTitle', 'moduleName') ?>
<?php $this->parentPageTitle = $this->translate('Not installed modules') ?>
<?php $this->subPageTitle = $this->translate('Delete the module')  ?>
<?php $this->moduleName = $this->translate($this->module_name) ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->moduleName) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('application/application-module-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-not-installed' // selected action is "list-not-installed"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'modules-administration',
            'action' => 'list-not-installed',
            'check_acl' => true
        ],
        'delete_module' => [
            'name' => $this->moduleName . ' - ' . $this->subPageTitle,
            'controller' => 'modules-administration',
            'action' => 'upload',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->subPageTitle,
    'body' => $this->partial('partial/form', ['form' => $this->moduleForm])
]) ?>