<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('List of installed modules') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('application/application-module-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-installed' // selected action is "list-installed"
]) ?>