<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Upload updates') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('application/application-module-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'upload-updates' // selected action is "upload-updates"
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Updates'),
    'body' => $this->partial('partial/form', ['form' => $this->module_form])
]) ?>