<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Upload a module') ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('Not installed modules')) ?>

<!-- render a header -->
<?php echo $this->render('application/application-module-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list-not-installed' // selected action is "list-not-installed"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('Not installed modules'),
            'controller' => 'modules-administration',
            'action' => 'list-not-installed',
            'check_acl' => true
        ],
        'upload_module' => [
            'name' => $this->subPageTitle,
            'controller' => 'modules-administration',
            'action' => 'upload',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('A new module'),
    'body' => $this->partial('partial/form', ['form' => $this->module_form])
]) ?>