<div class="col-md-4">
    <div class="thumbnail">
        <img style="height: <?php echo (int) $this->getSetting('membership_image_height') ?>px;" alt="<?php echo $this->escapeHtmlAttr($data->title) ?>" src="<?php echo $this->membershipImageUrl($data->image) ?>" />
        <div class="caption" >
            <div class="description">
                <h3><?php echo $this->escapeHtml($data->title) ?></h3>
                <h4><?php echo $this->escapeHtml($this->costFormat($data)) ?> <?php echo $this->escapeHtml($data->lifetime) ?> <?php echo $this->translatePlural('day', 'days', $data->lifetime) ?></h4>
                <p><?php echo $this->escapeHtml($data->description) ?></p>
            </div>
        </div>
        <div class="buttons">
            <a href="javascript:void(0)" rel="nofollow" onclick="payment.addToShoppingCart(<?php echo $data->id ?>, 'membership')" class="btn btn-primary" role="button">
                <?php echo $this->translate('Buy') ?>
            </a> 
            <a href="javascript:void(0)" rel="nofollow" class="btn btn-default" role="button" onclick="showPopup('<?php echo $this->escapeHtmlAttr($this->url('administration', array('controller' => 'acl', 'action' => 'ajax-get-resources', 'slug' => $data->role_id))) ?>', 'popup-acl-resources-window')">
                <?php echo $this->translate('Membership info') ?>
            </a>
        </div>
    </div>
</div>