<!-- include needed js and css files -->
<?php $this->layoutHeadScript()->appendFile($this->layoutAsset('membership.js', 'js', 'membership')) ?>
<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('main.css', 'css', 'membership')) ?>

<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('List of membership levels') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<!-- render the user menu -->
<?php echo $this->partial('partial/user-menu', array(
    'menu' => $this->userMenu(),
    'active_controller' => 'memberships',
    'active_action' => 'list'
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'home' => array(
            'name' => $this->translate('Home'),
            'controller' => 'Home',
            'action' => 'index',
            'check_acl' => false
        ),
        'membership_list' => array(
            'name' => $this->pageTitle,
            'controller' => 'memberships',
            'action' => 'list',
            'check_acl' => false
        )
    )
)) ?>

<div class="row">
    <div class="col-sm-6 col-md-3" id="purchased-memberships-wrapper">
        <?php echo $this->partial('membership/membership/purchased-units-list', array(
            'user_levels' => $this->user_levels
        )) ?>
    </div>
    <div class="col-sm-6 col-md-9" id="memberships-wrapper">
        <?php echo $this->partial('membership/membership/units-list', array(
            'paginator' => $this->paginator,
            'order_by' => $this->order_by,
            'order_type' => $this->order_type,
            'per_page' => $this->per_page,
        )) ?>
    </div>
</div>

<?php $this->inlineScript()->captureStart() ?>
    var membership = new Membership();
    membership.setServerUrl('<?php echo $this->url(null, array('controller' => 'memberships')) ?>');
    membership.setConfirmTitle('<?php echo $this->escapeJs($this->translate('Yes')) ?>');
    membership.setCancelTitle('<?php echo $this->escapeJs($this->translate('No')) ?>');
    membership.setContainer('purchased-memberships-wrapper');
<?php $this->inlineScript()->captureEnd() ?>
