<?php $this->declareVars('ajaxWrapper', 'ajaxCallback') ?>

<?php $this->ajaxWrapper  = 'memberships-wrapper' ?>
<?php $this->ajaxCallback = 'uniformHeight(\'#' . $this->ajaxWrapper . ' .thumbnail .description\', true)' ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title"><?php echo $this->translate('List of avaiable membership levels') ?></h4>
    </div>
    <div class="panel-body">
            <?php if(!$this->paginator->count()): ?>
                <div class="alert alert-warning"><?php echo $this->translate('Nothing found') ?></div>
            <?php else: ?>
                <?php echo $this->partial('partial/data-list', array(
                    'ajax_wrapper' => $this->ajaxWrapper,
                    'ajax' => true,
                    'ajax_callback' => 'function(){ ' . $this->ajaxCallback . ' }',
                    'paginator' => $this->paginator,
                    'patrial' => '/membership/membership/_unit',
                    'controller' => $this->currentRoute()->getController(),
                    'action' => $this->currentRoute()->getAction(),
                    'showPerPage' => true,
                    'order_by' => $this->order_by,
                    'order_type' => $this->order_type,
                    'per_page' => $this->per_page,
                    'orderList' => array(
                        'cost' => $this->translate('Cost'),
                        'title' => $this->translate('Title'),
                        'lifetime' => $this->translate('Lifetime in days')
                    )
                )) ?>

                <?php $this->inlineScript()->captureStart() ?>
                    <?php echo $this->ajaxCallback ?>
                <?php $this->inlineScript()->captureEnd() ?>
            <?php endif; ?>
    </div>
</div>