<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Have you forgotten your password or nickname?') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<h1><?php echo $this->escapeHtml($this->pageTitle); ?></h1>

<!-- render a form -->
<?php echo $this->partial('partials/form', array(
    'form' => $this->forgotForm,
    'controller' => 'user',
    'action' => 'forgot',
    'categoriesAlwaysOpened' => true
)); ?>