<?php
$title = $this->translate('Login');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php echo $this->partial('notifications') ?>

<?php
$form = $this->loginForm;
$form->setAttribute('action', $this->url('application', array('controller' => 'login')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>
