<?php $this->declareVars('baseTabs', 'subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Clear cache') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('application/settings-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partials/tabs', array(
    'tabs' => $this->baseTabs,
    'active' => 'clear-cache' // selected action is "clear_cache"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partials/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->subPageTitle,
            'controller' => 'settings-administration',
            'action' => 'clear-cache',
            'check_acl' => true
        )
    )
)) ?>

<!-- render a form -->
<?php echo $this->partial('partials/form', array(
    'form' => $this->cacheForm,
    'controller' => 'settings-administration',
    'action' => 'clear-cache'
)); ?>