<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Site settings') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<?php
  $this->baseTabs = array(
    'list' => array(
        'name' => $this->translate('List of settings'),
        'controller' => 'settings-administration',
        'action' => 'index',
        'check_acl' => true
    ),
    'clear_cache' => array(
        'name' => $this->translate('Clear cache'),
        'controller' => 'settings-administration',
        'action' => 'clear-cache',
        'check_acl' => true
    )
  );
?>

<div class="page-header">
  <h1>
    <img src="<?php  echo $this->layoutAsset('icon/setting.png', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
    <?php echo $this->escapeHtml($this->pageTitle) ?>
  </h1>
</div>
