<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Site settings') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<div class="page-header">
  <h1>
    <img src="<?php  echo $this->asset('icons/settings.png', 'images') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
    <?php echo $this->escapeHtml($this->pageTitle) ?>
  </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
  $this->baseTabs = array(
      'list' => array(
      'name' => $this->translate('List of settings'),
      'controller' => 'settings-administration',
      'action' => 'index',
      'check_acl' => true
    ) 
  );
?>