<?php $this->declareVars('baseUrl') ?>

<ul class="nav nav-tabs">
    <?php foreach ($this->aclRoutePermission($this->tabs) as $tab) : ?>
        <?php
            // get a base url
            $this->baseUrl = [
                'controller' => $tab['controller'],
                'action' => $tab['action']
            ];

            // get extra url params
            if (!empty($tab['params']) && is_array($tab['params'])) {
                $this->baseUrl = array_merge($this->baseUrl, $tab['params']);    
            }
        ?>

        <li<?php if (!empty($this->active) &&  $this->active == $tab['action']): ?> class="active"<?php endif ?>>
            <a href="<?php echo $this->url('application/page', $this->baseUrl, ['force_canonical' => true]) ?>">
                <?php echo $tab['name'] ?>
            </a>
        </li>
    <?php endforeach ?>
</ul>