<?php echo $this->doctype(); ?>
<html dir="<?php echo $this->localization()->getCurrentLanguageDirection() ?>" lang="<?php echo $this->localization()->getCurrentLanguage() ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->getSetting('application_site_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1')
            ->appendName('generator', $this->getSetting('application_generator') . ' ' . $this->getSetting('application_generator_version'))
            ->appendName('description', $this->getSetting('application_meta_description'))
            ->appendName('keywords', $this->getSetting('application_meta_keywords'));
        ?>

        <!-- Le styles -->
        <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->asset('icon/favicon.ico', 'image')))
            ->prependStylesheet($this->asset(($this->localization()->isCurrentLanguageLtr() ? 'administration.css' : 'administration.rtl.css'), 'css')) 
            ->prependStylesheet($this->asset('jquery-ui.css', 'css'))
            ->prependStylesheet($this->asset('bootstrap-theme.css', 'css'))
            ->prependStylesheet($this->asset('bootstrap.css', 'css'))
        ?>

        <?php if (!$this->localization()->isCurrentLanguageLtr()): ?>
            <?php $this->headLink()->appendStylesheet($this->asset('bootstrap.rtl.css', 'css')) ?>
        <?php endif; ?>

        <?php echo $this->headLink() ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->asset('functions.js'))
            ->prependFile($this->asset('jquery.cookie.js'))
            ->prependFile($this->asset('bootstrap.js'))
            ->prependFile($this->asset('jquery-ui.js'))            
            ->prependFile($this->asset('jquery-1.11.0.js'))
            ->prependFile($this->asset('respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
            ->prependFile($this->asset('html5shiv.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
        ?>
    </head>
    <body>

        <!-- nav bar -->
        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="http://dream-cms.com">
                        <?php echo $this->getSetting('application_generator') . ' ' . $this->getSetting('application_generator_version') ?>
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-<?php if ($this->localization()->isCurrentLanguageLtr()): ?>left<?php else: ?>right<?php endif; ?>">
                        <?php echo $this->partial('partial/admin_menu', array(
                            'title' => $this->translate('Select Part')
                        )) ?>
                        <?php if (count($this->localization()->getAllLocalizations()) > 1): ?>
                            <!-- select language -->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-globe"></span>
                                    <?php echo $this->translate('Select language') ?><b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php foreach ($this->localization()->getAllLocalizations() as $localization) : ?>
                                        <li <?php if ($this->localization()->getCurrentLanguage() == $localization['language']): ?>class="disabled"<?php endif; ?>>
                                            <a href="<?php echo  $this->url(null, array_merge(array(
                                                    'languge' => $localization['language'],
                                                    'controller' => $this->currentRoute()->getController(),
                                                    'action' => $this->currentRoute()->getAction()
                                                    ),  $this->currentRoute()->getExtraRouteParams()), array('query' => $this->currentRoute()->getQuery())) ?>">

                                                <img src="<?php  echo $this->asset('icon/flag/' . $localization['language'] . '.gif', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->translate($localization['description'])) ?>" />
                                                <?php echo $localization['description'] ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>
                    <ul class="nav navbar-nav navbar-<?php if ($this->localization()->isCurrentLanguageLtr()): ?>right<?php else: ?>left<?php endif; ?>">
                        <li>
                            <a href="<?php echo  $this->url('application') ?>">
                                <span class="glyphicon glyphicon-home"></span>
                                <?php echo $this->translate('Back to site') ?>
                            </a>
                        </li>
                        <?php if (!$this->isGuest()): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-user"></span>
                                    <?php echo sprintf($this->translate('Welcome'), $this->userIdentity()->nick_name) ?><b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php if ($this->checkPermission('users_administration_edit_user')): ?>
                                        <li>
                                            <a href="<?php echo  $this->url('application', array('controller' => 'users-administration', 'action' => 'edit-user', 'slug' => $this->userIdentity()->user_id)) ?>">
                                                <span class="glyphicon glyphicon-edit"></span>
                                                <?php echo $this->translate('Edit account') ?>
                                            </a>
                                        </li>
                                    <?php endif; ?>
                                    <li>
                                        <a href="<?php echo  $this->url('application', array('controller' => 'user', 'action' => 'logout')) ?>">
                                            <span class="glyphicon glyphicon-off"></span>
                                            <?php echo $this->translate('Logout') ?>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <!-- container -->
        <div class="container" id="container">
