<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->getSetting('application_site_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('generator', $this->getSetting('application_generator') . ' ' . $this->getSetting('application_generator_version'))
            ->appendName('description', $this->getSetting('application_meta_description'))
            ->appendName('keywords', $this->getSetting('application_meta_keywords'));
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->asset('icons/favicon.ico', 'images')))
                ->prependStylesheet($this->asset('bootstrap-responsive.css', 'css'))
                ->prependStylesheet($this->asset('bootstrap.css', 'css'))
                ->appendStylesheet($this->asset('administration.css', 'css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->asset('html5.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
                ->prependFile($this->asset('bootstrap.js'))
                ->prependFile($this->asset('jquery-1.10.2.js')) ?>
    </head>
    <body>

        <!-- nav bar -->
        <div class="navbar">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="http://dream-cms.com">
                        <?php echo $this->getSetting('application_generator') . ' ' . $this->getSetting('application_generator_version') ?>
                    </a>
                    <div class="nav-collapse">
                        <!-- left menu items -->
                        <ul class="nav">
                            <?php if (count($this->adminMenu())): ?>
                                <!-- select part -->
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-bookmark"></i>
                                        <?php echo $this->translate('Select Part') ?><b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($this->adminMenu() as $menuItem) : ?>
                                            <li <?php if ($this->currentRoute()->getController() == $menuItem['controller']): ?>class="disabled"<?php endif; ?>>
                                                <a href="<?php echo  $this->url(null, array('controller' => $menuItem['controller'], 'action' => $menuItem['action'])) ?>">
                                                    <?php echo $this->translate($menuItem['name']) ?>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                            <?php if (count($this->localizations()->getAllLocalizations()) > 1): ?>
                                <!-- select language -->
                                <li class="divider-vertical"></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-globe"></i>
                                        <?php echo $this->translate('Select language') ?><b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <?php foreach ($this->localizations()->getAllLocalizations() as $localization) : ?>
                                            <li <?php if ($this->localizations()->getCurrentLocalization()['language'] == $localization['language']): ?>class="disabled"<?php endif; ?>>
                                                <a href="<?php echo  $this->url(null, array_merge(array(
                                                        'languge' => $localization['language'],
                                                        'controller' => $this->currentRoute()->getController(),
                                                        'action' => $this->currentRoute()->getAction()
                                                        ),  $this->currentRoute()->getExtraRouteParams()), array('query' => $this->currentRoute()->getQuery())) ?>">

                                                    <img src="<?php  echo $this->asset('icons/flags/' . $localization['language'] . '.gif', 'images') ?>" alt="<?php echo $this->escapeHtmlAttr($this->translate($localization['description'])) ?>" />
                                                    <?php echo $localization['description'] ?>
                                                </a>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                        <!-- right menu items -->
                        <ul class="nav pull-right">
                            <li>
                                <a href="<?php echo  $this->url('application', array('controller' => 'home')) ?>">
                                    <i class="icon-home"></i>
                                    <?php echo $this->translate('Back to site') ?>
                                </a>
                            </li>
                            <?php if (!$this->isGuest()): ?>
                                <li class="divider-vertical"></li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="icon-user"></i>
                                        <?php echo sprintf($this->translate('Welcome'), $this->userIdentity()->nick_name) ?><b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="<?php echo  $this->url('application', array('controller' => 'logout')) ?>">
                                                <i class="icon-off"></i>
                                                <?php echo $this->translate('Logout') ?>
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div><!-- /navbar-inner -->
        </div>

        <!-- container -->
        <div class="container" id="container">
