            <footer>
                <div class="row">
                	<div class="col-lg-3 col-md-3 col-sm-6">
                		<div class="links">
                			<h4><a href="#">Information</a></h4>
                			<ul>
                				<li><a href="about.html">About Us</a></li>
                				<li><a href="typography.html">Policy Privacy</a></li>
                				<li><a href="typography.html">Terms and Conditions</a></li>
                				<li><a href="typography.html">Shipping Methods</a></li>
                			</ul>
                		</div>
                	</div>
                	<div class="col-lg-3 col-md-3 col-sm-6">
                		<div class="links">
                			<h4><a href="#">Categories</a></h4>
                			<ul>
                				<li><a href="catalogue.html">Cras justo odio</a></li>
                				<li><a href="catalogue.html">Dapibus ac facilisis in</a></li>
                				<li><a href="catalogue.html">Morbi leo risus</a></li>
                				<li><a href="catalogue.html">Porta ac consectetur ac</a></li>
                				<li><a href="catalogue.html">Porta ac consectetur ac</a></li>
                			</ul>
                		</div>
                	</div>
                	<div class="col-lg-3 col-md-3 col-sm-6">
                		<div class="links">
                			<h4><a href="#">Customer Service</a></h4>
                			<ul>
                				<li><a href="contact.html">Contact Us</a></li>
                				<li><a href="#">YM: erwin_heldy</a></li>
                				<li><a href="#">Telp: 087825376xxx</a></li>
                				<li><a href="#">Email: erwin.heldy@gmail.com</a></li>
                			</ul>
                		</div>
                	</div>
                	<div class="col-lg-3 col-md-3 col-sm-6">
                		<div class="links">
                			<h4><a href="#">Follow Us</a></h4>
                			<ul>
                				<li><a href="#">Google Plus</a></li>
                				<li><a href="#">Facebook</a></li>
                				<li><a href="#">Twitter</a></li>
                				<li><a href="#">RSS Feed</a></li>
                			</ul>
                		</div>
                	</div>
                </div>
                <div class="row">
                    <p class="text-center">&copy; <?php echo date('Y') ?> <?php echo $this->applicationSetting('application_site_name') ?></p>
                </div>
                <?php echo $this->pageInjectWidget('footer') ?>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>