            <footer>
                <?php echo $this->pageInjectWidget('footer') ?>
                <?php echo $this->pageFooterMenu(4 /* max columns per row */) ?>
                <br />
                <div class="row">
                    <p class="text-center">&copy; <?php echo date('Y') ?> <?php echo $this->applicationSetting('application_site_name') ?></p>
                </div>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>