<?php echo $this->doctype(); ?>
<html dir="<?php echo $this->localization()->getCurrentLanguageDirection() ?>" lang="<?php echo $this->localization()->getCurrentLanguage() ?>">
    <head>
        <?php echo $this->pageInjectWidget('head') ?>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->applicationSetting('application_site_name'))->setSeparator(' - ')->setAutoEscape(false)->setTranslatorEnabled(false) ?>

        <?php echo $this->headMeta()
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('viewport', 'width=device-width, initial-scale=1')
            ->appendName('generator', $this->applicationSetting('application_generator') . ' ' . $this->applicationSetting('application_generator_version'))
        ?>

        <!-- styles -->
        <?php $this->layoutHeadLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->layoutAsset('icon/favicon.ico', 'image')])
            ->prependStylesheet($this->layoutAsset('frontend.css', 'css')) 
            ->prependStylesheet($this->layoutAsset('jquery-ui.css', 'css'))
            ->prependStylesheet($this->layoutAsset('sm-simple.css', 'css'))
            ->prependStylesheet($this->layoutAsset('sm-core-css.css', 'css'))
            ->prependStylesheet($this->layoutAsset('bootstrap-theme.css', 'css'))
            ->prependStylesheet($this->layoutAsset('bootstrap.css', 'css'))
        ?>

        <?php if (!$this->localization()->isCurrentLanguageLtr()): ?>
            <?php $this->layoutHeadLink()
                ->appendStylesheet($this->layoutAsset('bootstrap.rtl.css', 'css'))
                ->appendStylesheet($this->layoutAsset('frontend.rtl.css', 'css'))?>
        <?php endif; ?>

        <?php echo $this->layoutHeadLink() ?>

        <!-- scripts -->
        <?php echo $this->layoutHeadScript()
            ->prependFile($this->layoutAsset('jquery.smartmenus.js'))
            ->prependFile($this->layoutAsset('functions.js'))
            ->prependFile($this->layoutAsset('jquery.cookie.js'))
            ->prependFile($this->layoutAsset('bootstrap.js'))
            ->prependFile($this->layoutAsset('jquery-ui.js'))            
            ->prependFile($this->layoutAsset('jquery.js'))
            ->prependFile($this->layoutAsset('respond.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
            ->prependFile($this->layoutAsset('html5shiv.js'), 'text/javascript', ['conditional' => 'lt IE 9'])
        ?>
    </head>
    <body>
        <!-- container -->
        <div class="container" id="container">
        <?php echo $this->pageInjectWidget('body') ?>
        <div id="logo-wrapper">
            <div class="row">
                <div class="col-sm-7" id="logo-image">
                    <h1>
                        <a href="<?php echo $this->url('page') ?>">
                            <img src="<?php echo $this->layoutAsset('logo.png', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->applicationSetting('application_site_name')) ?>" title="<?php echo $this->escapeHtmlAttr($this->applicationSetting('application_site_name')) ?>" /></a>
                        <?php echo $this->applicationSetting('application_site_name') ?> 
                    </h1>
                </div>
                <div class="col-sm-5" id="logo-actions">
                    <?php echo $this->pageInjectWidget('logo') ?>
                    <?php if (count($this->localization()->getAllLocalizations()) > 1): ?>
                        <?php $this->declareVars('languageParams') ?>
                        <!-- language switcher -->
                        <div class="btn-group">
                            <div class="btn-group-wrapper">
                                <div class="btn-group-item">
                                    <div class="dropdown">
                                        <img src="<?php  echo $this->layoutAsset('icon/flag/' . $this->escapeHtml($this->localization()->getCurrentLocalization()['language']) . '.gif', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($this->localization()->getCurrentLocalization()['description']) ?>" />
                                        <a class="dropdown-toggle text-capitalize" data-toggle="dropdown" href="#"><?php echo $this->escapeHtml($this->localization()->getCurrentLocalization()['language']) ?><span class="caret"></span></a>
                                        <ul class="dropdown-menu <?php if ($this->localization()->isCurrentLanguageLtr()): ?>dropdown-menu-right<?php else: ?>dropdown-menu-left<?php endif ?>" role="menu">
                                            <?php foreach ($this->localization()->getAllLocalizations() as $language): ?>
                                                <li role="presentation" <?php if ($language['language'] == $this->localization()->getCurrentLanguage()): ?>class="disabled"<?php endif ?>>

                                                    <?php $this->languageParams = false !== $this->pageUrl($this->page['slug'], $language['language']) 
                                                            ? ['language' => $language['language'], 'page_name' => $this->pageUrl($this->page['slug'], $language['language'])]
                                                            : ['language' => $language['language']] ?>

                                                    <a role="menuitem" tabindex="-1" href="<?php echo $this->url('page', $this->languageParams, ['force_canonical' => true]) ?>">
                                                        <img src="<?php  echo $this->layoutAsset('icon/flag/' . $this->escapeHtml($language['language']) . '.gif', 'image') ?>" alt="<?php echo $this->escapeHtmlAttr($language['description']) ?>" />
                                                        <?php echo $this->escapeHtml($language['description']) ?>
                                                    </a>
                                                </li>
                                            <?php endforeach ?>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif?>
                    <?php if(!$this->userIsGuest()): ?>
                        <div class="btn-group">
                            <!-- user menu -->
                            <div class="btn-group-wrapper">
                                <div class="btn-group-item">
                                    <div class="dropdown">
                                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                            <?php echo $this->translate('Hello') ?>, <?php echo $this->escapeHtml($this->userIdentity()['nick_name']) ?><span class="caret"></span></a>
                                        <img class="icon" alt="<?php echo $this->escapeHtmlAttr($this->userIdentity()['nick_name']) ?>" src="<?php echo $this->escapeHtmlAttr($this->userAvatarUrl($this->userIdentity()['avatar'])) ?>" />
                                        <ul class="dropdown-menu <?php if ($this->localization()->isCurrentLanguageLtr()): ?>dropdown-menu-right<?php else: ?>dropdown-menu-left<?php endif ?>" role="menu">
                                            <?php if ($this->pageUserMenu()): ?>
                                                <?php foreach($this->pageUserMenu() as $menu) : ?>
                                                    <li role="presentation">
                                                        <a role="menuitem" tabindex="-1" href="<?php echo $this->url('page', ['page_name' => $menu['url']], ['force_canonical' => true]) ?>"><?php echo $menu['title'] ?></a>
                                                    </li>
                                                <?php endforeach ?>
                                                <li role="presentation" class="divider"></li>
                                            <?php endif ?>
                                            <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0)" onclick="ajaxQuery('<?php echo $this->url('page', ['page_name' => $this->url], ['force_canonical' => true]) ?>')"><?php echo $this->translate('Logout') ?></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        </div>
        <?php echo $this->pageMenu() ?>