<?php echo $this->doctype(); ?>
<html dir="<?php echo $this->localizations()->getCurrentLanguageDirection() ?>" lang="<?php echo $this->localizations()->getCurrentLanguage() ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->getSetting('application_site_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('generator', $this->getSetting('application_generator') . ' ' . $this->getSetting('application_generator_version'))
            ->appendName('description', $this->getSetting('application_meta_description'))
            ->appendName('keywords', $this->getSetting('application_meta_keywords'));
        ?>

        <!-- Le styles -->
        <?php $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->asset('icons/favicon.ico', 'images')))
                ->prependStylesheet($this->asset('bootstrap-theme.css', 'css'))
                ->prependStylesheet($this->asset('bootstrap.css', 'css'))
                ->appendStylesheet($this->asset('jquery-ui.css', 'css'))
                ->appendStylesheet($this->asset(($this->localizations()->isCurrentLanguageLtr() ? 'frontend.css' : 'frontend.rtl.css'), 'css')) ?>

        <?php if (!$this->localizations()->isCurrentLanguageLtr()): ?>
            <?php $this->headLink()->appendStylesheet($this->asset('bootstrap.rtl.css', 'css')) ?>
        <?php endif; ?>

        <?php echo $this->headLink() ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->asset('jquery-1.10.2.js'))
                ->appendFile($this->asset('bootstrap.js'))
                ->appendFile($this->asset('jquery-ui.js'))
                ->appendFile($this->asset('html5.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
        ?>
    </head>
    <body>

        <!-- container -->
        <div class="container" id="container">
