<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->getSetting('application_site_name'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('generator', $this->getSetting('application_generator') . ' ' . $this->getSetting('application_generator_version'))
            ->appendName('description', $this->getSetting('application_meta_description'))
            ->appendName('keywords', $this->getSetting('application_meta_keywords'));
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->asset('icons/favicon.ico', 'images')))
                        ->prependStylesheet($this->asset('bootstrap-responsive.min.css', 'css'))
                        ->prependStylesheet($this->asset('style.css', 'css'))
                       ->prependStylesheet($this->asset('bootstrap.min.css', 'css')) ?>

        <!-- Scripts -->

        <?php echo $this->headScript()
                ->prependFile($this->asset('html5.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
                ->prependFile($this->asset('functions.js'))
                ->prependFile($this->asset('bootstrap.min.js'))
                ->prependFile($this->asset('jquery.min.js')) ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="http://www.screamingpower.ca"><?php echo $this->translate('Screaming Power') ?></a>
                    <div class="nav-collapse collapse">
                            <ul class="nav">
                                <li><a href="<?php echo $this->url('application') ?>">Home</a></li>
                            </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container" id="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2013 screamingpower.ca</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
