<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Test\UserBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
  'User\Test\Service\ServiceTest'                => __DIR__ . '/test/User/src/User/Service/ServiceTest.php',
  'User\Module'                                  => __DIR__ . '/Module.php',
  'User\Form\Role'                               => __DIR__ . '/src/User/Form/Role.php',
  'User\Form\ActivationCode'                     => __DIR__ . '/src/User/Form/ActivationCode.php',
  'User\Form\Delete'                             => __DIR__ . '/src/User/Form/Delete.php',
  'User\Form\Forgot'                             => __DIR__ . '/src/User/Form/Forgot.php',
  'User\Form\Login'                              => __DIR__ . '/src/User/Form/Login.php',
  'User\Form\UserFilter'                         => __DIR__ . '/src/User/Form/UserFilter.php',
  'User\Form\User'                               => __DIR__ . '/src/User/Form/User.php',
  'User\Controller\UserAdministrationController' => __DIR__ . '/src/User/Controller/UserAdministrationController.php',
  'User\Controller\UserController'               => __DIR__ . '/src/User/Controller/UserController.php',
  'User\View\Helper\UserAvatarUrl'               => __DIR__ . '/src/User/View/Helper/UserAvatarUrl.php',
  'User\Event\Event'                             => __DIR__ . '/src/User/Event/Event.php',
  'User\Service\Service'                         => __DIR__ . '/src/User/Service/Service.php',
  'User\Model\User'                              => __DIR__ . '/src/User/Model/User.php',
  'User\Model\XmlRpc'                            => __DIR__ . '/src/User/Model/XmlRpc.php',
  'User\Model\Base'                              => __DIR__ . '/src/User/Model/Base.php',
  'User\Model\UserAdministration'                => __DIR__ . '/src/User/Model/UserAdministration.php',
  'User\XmlRpc\Handler'                          => __DIR__ . '/src/User/XmlRpc/Handler.php',
);
