<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Test\UserBootstrap'                   => __DIR__ . '/test/Bootstrap.php',
  'User\Test\Controller\LogoutControllerTest' => __DIR__ . '/test/User/src/User/Controller/LogoutControllerTest.php',
  'User\Test\Controller\LoginControllerTest'  => __DIR__ . '/test/User/src/User/Controller/LoginControllerTest.php',
  'User\Test\Service\ServiceTest'             => __DIR__ . '/test/User/src/User/Service/ServiceTest.php',
  'User\Module'                               => __DIR__ . '/Module.php',
  'User\Form\Login'                           => __DIR__ . '/src/User/Form/Login.php',
  'User\Controller\LogoutController'          => __DIR__ . '/src/User/Controller/LogoutController.php',
  'User\Controller\BaseController'            => __DIR__ . '/src/User/Controller/BaseController.php',
  'User\Controller\LoginController'           => __DIR__ . '/src/User/Controller/LoginController.php',
  'User\Event\Event'                          => __DIR__ . '/src/User/Event/Event.php',
  'User\Service\Service'                      => __DIR__ . '/src/User/Service/Service.php',
  'User\Model\XmlRpc'                         => __DIR__ . '/src/User/Model/XmlRpc.php',
  'User\Model\Base'                           => __DIR__ . '/src/User/Model/Base.php',
  'User\XmlRpc\Handler'                       => __DIR__ . '/src/User/XmlRpc/Handler.php',
);
