<?php $this->headMeta()->appendName('description', $this->page['meta_description'] 
        ? $this->page['meta_description'] 
        : $this->applicationSetting('application_meta_description')) ?>

<?php $this->headMeta()->appendName('keywords', $this->page['meta_keywords'] 
        ? $this->page['meta_keywords'] 
        : $this->applicationSetting('application_meta_keywords')) ?>

<?php if ($this->page['level'] > 1): ?>
    <?php $this->pageTitle($this->breadcrumb) ?>
    <?php echo $this->partial('page/partial/breadcrumb', ['breadcrumb' => $this->breadcrumb, 'page' => $this->page]) ?>
<?php endif ?>