<?php $this->headMeta()->appendName('description', $this->page['meta_description'] 
        ? $this->page['meta_description'] 
        : $this->applicationSetting('application_meta_description')) ?>

<?php $this->headMeta()->appendName('keywords', $this->page['meta_keywords'] 
        ? $this->page['meta_keywords'] 
        : $this->applicationSetting('application_meta_keywords')) ?>

<?php echo $this->pageBreadcrumb()
        ->setBreadcrumb($this->breadcrumb)->setPage($this->page)->getBreadcrumb() ?>

<?php echo $this->partial('partial/notification') ?>