<div class="modal fade" id="popup-shopping-cart-window">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Add the item to the shopping cart') ?></h4>
            </div>
            <div class="modal-body">
                <?php if ($this->shoppingCartForm) : ?>
                    <!-- render a form -->
                    <?php echo $this->partial('partial/form', array(
                        'form' => $this->shoppingCartForm,
                        'controller' => $this->currentRoute()->getController(),
                        'action' => $this->currentRoute()->getAction()
                    )); ?>
                <?php endif; ?>

                <?php if ($this->message) : ?>
                    <p><?php echo $this->message ?></p>
                <?php endif; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>

                <?php if ($this->shoppingCartForm) : ?>
                    <button type="button" onclick="payment.sendShoppingCartForm()" class="btn btn-primary"><?php echo $this->translate('Add') ?></button>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $("#popup-shopping-cart-window").find("form:first").bind('submit', function() {
            payment.sendShoppingCartForm();
            return false;
        });

        <?php if ($this->updateShopingCart) : ?>
            payment.updateShoppingCart();
        <?php endif; ?>
    </script>
</div>
