<?php $this->placeholder('content')->captureStart() ?>
    <?php if ($this->shoppingCartForm) : ?>
        <!-- render a form -->
        <?php echo $this->partial('partial/form', array(
            'form' => $this->shoppingCartForm,
            'controller' => $this->currentRoute()->getController(),
            'action' => $this->currentRoute()->getAction()
        )); ?>
    <?php endif; ?>

    <?php if ($this->message) : ?>
        <p><?php echo $this->message ?></p>
    <?php endif; ?>
<?php $this->placeholder('content')->captureEnd() ?>

<?php $this->placeholder('contentFooter')->captureStart() ?>
    <?php if ($this->shoppingCartForm) : ?>
        <button type="button" onclick="payment.sendShoppingCartForm()" class="btn btn-primary"><?php echo $this->translate('Add') ?></button>
    <?php endif; ?>

    <script type="text/javascript">
        $("#popup-shopping-cart-window").find("form:first").bind('submit', function() {
            payment.sendShoppingCartForm();
            return false;
        });

        <?php if ($this->updateShopingCart) : ?>
            payment.updateShoppingCart();
        <?php endif; ?>
    </script>
<?php $this->placeholder('contentFooter')->captureEnd() ?>

<?php 
    echo $this->partial('partial/popup', array(
        'popup_id' => 'popup-shopping-cart-window',
        'title' => 'Add the item to the shopping cart',
        'body' => $this->placeholder('content'),
        'footer' => $this->placeholder('contentFooter')
    )) 
?>