<div class="modal fade" id="popup-shopping-cart-window">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Edit the item') ?></h4>
            </div>
            <div class="modal-body">
                <?php if ($this->shoppingCartForm) : ?>
                    <!-- render a form -->
                    <?php echo $this->partial('partial/form', array(
                        'form' => $this->shoppingCartForm,
                        'controller' => $this->currentRoute()->getController(),
                        'action' => $this->currentRoute()->getAction()
                    )); ?>
                <?php endif; ?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                <button type="button" id="popup-shopping-cart-submit" onclick="payment.sendEditItemForm('<?php echo $this->escapeJs($this->id) ?>')" class="btn btn-primary"><?php echo $this->translate('Submit') ?></button>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        $("#popup-shopping-cart-window").find("form:first").bind('submit', function() {
            payment.sendEditItemForm('<?php echo $this->escapeJs($this->id) ?>');
            return false;
        });

        <?php if ($this->refreshPage) : ?>
            payment.hidePopupShopping();
            payment.refreshPage();
        <?php endif; ?>
    </script>
</div>
