<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('List of transactions') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<!-- render user menu -->
<?php echo $this->partial('partial/user_menu', array(
    'menu' => $this->userMenu(),
    'active_controller' => 'payments',
    'active_action' => 'list'
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'home' => array(
            'name' => $this->translate('Home'),
            'controller' => 'Home',
            'action' => 'index',
            'check_acl' => false
        ),
        'payments_list' => array(
            'name' => $this->pageTitle,
            'controller' => 'payments',
            'action' => 'list',
            'check_acl' => false
        )
    )
)) ?>

<!-- render a data grid -->
<?php echo $this->partial('partial/data_grid', array(
    'controller' => 'payments',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => array(
        0 => array(
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ),
        1 => array(
            'title' => $this->translate('Code'),
            'order_name' => 'slug'
        ),
        2 => array(
            'title' => $this->translate('Paid'),
            'order_name' => 'paid'
        ),
        4 => array(
            'title' => $this->translate('Total amount'),
            'order_name' => 'cost'
        ),
        5 => array(
            'title' => $this->translate('Date'),
            'order_name' => 'date'
        )
    ),
    'paginator' => $this->paginator,
    'skipped_fields' => array(
        'currency',
        'items_count'
    ),
    'helpers' => array(
        'paid' => 'booleanValue',
        'cost' => 'costFormat',
        'date' => 'date',
        'payment' => 'translate',
    ),
    'helpers_set_array' => array(
        'cost' => true
    ),
    'helpers_options' => array(
        'date' => array(
            'type' => 'date'
        )
    ),
    'actions' => array(
        'regular_actions' => array(
        ),
        'multiple_actions' => array(
            0 => array(
                'name' => $this->translate('Delete selected'),
                'controller' => 'payments',
                'action' => 'delete-transactions',
                'check_acl' => false,
                'confirm' => $this->translate('Selected transactions will be deleted. Are you sure?')
            ),
        ),
        'single_actions' => array (
            1 => array(
                'name' => $this->translate('View the transaction\'s items'),
                'controller' => 'payments',
                'action' => 'view-transaction-items',
                'check_acl' => false,
                'image' => $this->asset('icon/browse_action.png', 'image')
            ),
            2 => array(
                'name' => $this->translate('Buy items'),
                'controller' => 'payments',
                'action' => 'buy',
                'check_acl' => false,
                'image' => $this->asset('icon/buy_action.png', 'image', 'payment'),
                'param' => 'slug'
            ),
        )
    ),
    'actions_options' => array(
        'action_identity' => 'id',
        'form_name' => 'transactions',
        'multiple_actions' => array(
            'items_name' => 'transactions[]'
        )
    ),
    'actions_extra_check' => array(
        'single_actions' => array(
            'buy' => array(
                0 => array(
                    'function' => function($data) use ($payment_types, $current_currency) {
                        if (!$data['items_count'] || !count($payment_types) || Payment\Model\Base::TRANSACTION_PAID == $data['paid']
                                || $data['currency'] != $current_currency['code']) {

                            return false;
                        }

                        return true;
                    }
                )
            )
        )
    )
)) ?>