<?php use Payment\Model\Base as  BaseModel ?>

<?php $this->declareVars('pageTitle', 'regularActions') ?>
<?php $this->pageTitle = $this->translate('Shopping cart') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'home' => array(
            'name' => $this->translate('Home'),
            'controller' => 'Home',
            'action' => 'index',
            'check_acl' => false
        ),
        'shopping_cart' => array(
            'name' => $this->pageTitle,
            'controller' => 'payments',
            'action' => 'shopping-cart',
            'check_acl' => false
        )
    )
)) ?>

<?php
    if ($this->shoppingCart()->getItemsCount()) {
        $this->regularActions = array(
            0 => array(
                'name' => !$this->shoppingCart()->getCurrentDiscount()
                    ? $this->translate('Enter a discount code')
                    : $this->translate('Deactivate the discount code'),
                'js' => !$this->shoppingCart()->getCurrentDiscount()
                    ? 'payment.getDiscountCouponForm()'
                    : 'payment.deactivateDiscountCoupon()',
                'check_acl' => false,
            ),
            1 => array(
                'name' => $this->translate('Checkout'),
                'controller' => 'payments',
                'action' => 'checkout',
                'check_acl' => false
            )
        );
    }
?>

<!-- render a data grid -->
<?php echo $this->partial('partial/data-grid', array(
    'controller' => $this->currentRoute()->getController(),
    'action' => 'shopping-cart',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'headers' => array(
        0 => array(
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ),
        1 => array(
            'title' => $this->translate('Title'),
            'order_name' => 'title'
        ),
        2 => array(
            'title' => $this->translate('Unit Price'),
            'order_name' => 'cost'
        ),
        3 => array(
            'title' => $this->translate('Discount'),
            'order_name' => 'discount'
        ),
        4 => array(
            'title' => $this->translate('Count'),
            'order_name' => 'count'
        ),
        5 => array(
            'title' => $this->translate('Total price'),
            'order_name' => 'total'
        ),
        6 => array(
            'title' => $this->translate('Extra options')
        ),
        7 => array(
            'title' => $this->translate('Status')
        )
    ),
    'paginator' => $this->paginator,
    'skipped_fields' => array(
        'object_id',
        'view_controller',
        'view_action',
        'countable',
        'must_login',
        'slug',
        'available',
        'deleted',
        'multi_costs',
        'handler',
        'module_extra_options',
        'module_state'
    ),
    'helpers' => array(
        'title' => 'paymentItemLink',
        'active' => 'paymentItemStatus',
        'cost' => 'processCost',
        'discount' => 'processCost',
        'total' => 'processCost',
        'extra_options' => 'paymentItemExtraOptions'
    ),
    'helpers_set_array' => array(
        'active' => true,
        'title' => true,
        'extra_options' => true
    ),
    'helpers_options' => array(
    ),
    'actions' => array(
        'regular_actions' => $this->regularActions,
        'multiple_actions' => array(
            0 => array(
                'name' => $this->translate('Delete selected'),
                'controller' => $this->currentRoute()->getController(),
                'action' => 'delete-shopping-cart-items',
                'check_acl' => false,
                'confirm' => $this->translate('Selected items will be deleted. Are you sure?')
            )
        ),
        'single_actions' => array (
            0 => array(
                'name' => $this->translate('Edit'),
                'js' => 'payment.getEditItemForm(\'__value__\')',
                'check_acl' => false,
                'action' => 'edit-item',
                'image' => $this->asset('icon/edit_action.png', 'image')
            ),
        )
    ),
    'actions_options' => array(
        'action_identity' => 'id',
        'form_name' => 'shopping-cart',
        'multiple_actions' => array(
            'items_name' => 'items[]'
        )
    ),
    'actions_extra_check' => array(
        'single_actions' => array(
            'edit-item' => array(
                0 => array(
                    'param' => 'active',
                    'condition' =>  'return (int) "__value__" == "' . BaseModel::ITEM_ACTIVE . '";'
                ),
                1 => array(
                    'param' => 'available',
                    'condition' =>  'return (int) "__value__" == "' . BaseModel::ITEM_AVAILABLE . '";'
                ),
                2 => array(
                    'param' => 'deleted',
                    'condition' =>  'return (int) "__value__" == "' . BaseModel::ITEM_NOT_DELETED . '";'
                ),
                3 => array(
                    'param' => 'module_state',
                    'condition' =>  'return "__value__" == "' . BaseModel::MODULE_STATUS_ACTIVE . '";'
                ),
                4 => array(
                    'function' => function($data) use ($paymentHandlerManager) {
                        $paymentHandler = $paymentHandlerManager->getInstance($data['handler']);

                        if ($data['countable'] == BaseModel::MODULE_COUNTABLE ||
                                    $data['multi_costs'] == BaseModel::MODULE_MULTI_COSTS) {

                            return true;
                        }

                        if ($data['module_extra_options'] == BaseModel::MODULE_EXTRA_OPTIONS && $paymentHandler->
                                    getItemExtraOptions($data['object_id'])) {

                            return true;
                        }

                        // check a discount params
                        if ($data['discount'] || $paymentHandler->getDiscount($data['object_id'])) {
                            return true;
                        }

                        return false;
                    }
                )
            )
        )
    )
)) ?>

<?php if ($this->shoppingCart()->getItemsCount()) : ?>
    <div id="shopping-cart-price-wrapper">
        <p><b><?php echo $this->translate('Total price') ?>:</b> <?php echo $this->escapeHtml($this->processCost($this->shoppingCart()->getItemsDiscountedAmount(), true)) ?>
            <?php if ($this->shoppingCart()->getCurrentDiscount()) : ?>
                - <?php echo $this->translate('without discount') ?>: <?php echo $this->escapeHtml($this->processCost($this->shoppingCart()->getItemsAmount())) ?>
            <?php endif; ?>
        </p>
    </div>
<?php endif; ?>
