<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate($this->roleInfo['name']) ?>
<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->translate('List of roles')) ?>

<!-- render a header -->
<?php echo $this->render('acl/acl-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of roles'),
            'controller' => 'acl-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_resources' => [
            'name' => $this->subPageTitle,
            'controller' => 'acl-administration',
            'action' => 'browse-resources',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a data grid -->
<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'acl-administration',
    'action' => 'browse-resources',
    'slug' => $this->slug,
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        0 => [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        1 => [
            'title' => $this->translate('Description')
        ],
        2 => [
            'title' => $this->translate('Module')
        ],
        3 => [
            'title' => $this->translate('Status'),
            'order_name' => 'connection'
        ]
    ],
    'paginator' => $this->paginator,
    'helpers' => [
        'description' => 'translate',
        'module' => 'translate',
        'connection' => 'applicationBooleanValue'
    ],
    'helpers_options' => [
        'connection' => [
            'true_string' => $this->translate('Allowed'),
            'false_string' => $this->translate('Disallowed')
        ]
    ],
    'actions' => [
        'regular_actions' => [
        ],
        'multiple_actions' => [
            0 => [
                'name' => $this->translate('Allow selected'),
                'controller' => 'acl-administration',
                'action' => 'allow-resources',
                'params' => [
                    'slug' =>  $this->slug 
                ],
                'check_acl' => true
            ],
            1 => [
                'name' => $this->translate('Disallow selected'),
                'controller' => 'acl-administration',
                'action' => 'disallow-resources',
                'params' => [
                    'slug' =>  $this->slug 
                ],
                'check_acl' => true
            ]
        ],
        'single_actions' => [
            0 => [
                'name' => $this->translate('Resource\'s settings'),
                'controller' => 'acl-administration',
                'action' => 'resource-settings',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/setting_action.png', 'image'),
                'param' => 'connection'
            ],
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'acl-resources',
        'multiple_actions' => [
            'items_name' => 'resources[]'
        ]
    ],
    'actions_extra_check' => [
        'single_actions' => [
            'resource-settings' => [
                0 => [
                    'param' => 'connection',
                    'condition' =>  'return (int) "__value__" > 0;'
                ]
            ]
        ]
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Resources'),
    'body' => $this->content
]) ?>