<?php use Acl\Model\AclBase as AclBaseModel ?>
<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('List of roles') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('application/acl-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->subPageTitle,
            'controller' => 'acl-administration',
            'action' => 'list',
            'check_acl' => true
        )
    )
)) ?>

<!-- render a data grid -->
<?php echo $this->partial('partial/data-grid', array(
    'controller' => 'acl-administration',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => array(
        0 => array(
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ),
        1 => array(
            'title' => $this->translate('Name')
        ),
        2 => array(
            'title' => $this->translate('Type')
        )
    ),
    'paginator' => $this->paginator,
    'helpers' => array(
        'name' => 'translate',
        'type' => 'translate'
    ),
    'helpers_options' => array(
    ),
    'actions' => array(
        'regular_actions' => array(
            0 => array(
                'name' => $this->translate('Add a role'),
                'controller' => 'acl-administration',
                'action' => 'add-role',
                'check_acl' => true
            )
        ),
        'multiple_actions' => array(
            0 => array(
                'name' => $this->translate('Delete selected'),
                'controller' => 'acl-administration',
                'action' => 'delete-roles',
                'check_acl' => true,
                'confirm' => $this->translate('Selected roles will be deleted. Are you sure?')
            )
        ),
        'single_actions' => array(
            0 => array(
                'name' => $this->translate('Edit the role'),
                'controller' => 'acl-administration',
                'action' => 'edit-role',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/edit_action.png', 'image')
            ),
            1 => array(
                'name' => $this->translate('Browse resources'),
                'controller' => 'acl-administration',
                'action' => 'browse-resources',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/browse_action.png', 'image')
            )
        )
    ),
    'actions_options' => array(
        'action_identity' => 'id',
        'form_name' => 'acl-roles',
        'multiple_actions' => array(
            'items_name' => 'roles[]'
        )
    ),
    'actions_extra_check' => array(
        'multiple_actions' => array(
            'system_items' => array(
                'param' => 'type',
                'condition' =>  'return "__value__" == "' . AclBaseModel::ROLE_TYPE_SYSTEM . '" ? false : true;'
            )
        ),
        'single_actions' => array(
            'edit-role' => array(
                0 => array(
                    'param' => 'type',
                    'condition' =>  'return "__value__" == "' . AclBaseModel::ROLE_TYPE_SYSTEM . '" ? false : true;'
                )
            ),
            'browse-resources' => array(
                0 => array(
                    'param' => 'id',
                    'condition' =>  'return "__value__" == "' . AclBaseModel::DEFAULT_ROLE_ADMIN . '" ? false : true;'
                )
            )
        )
    )
)) ?>
