<?php use Acl\Model\AclBase as AclBaseModel ?>

<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of roles') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('acl/acl-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'acl-administration',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        0 => [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        1 => [
            'title' => $this->translate('Name')
        ],
        2 => [
            'title' => $this->translate('Type')
        ]
    ],
    'paginator' => $this->paginator,
    'helpers' => [
        'name' => 'translate',
        'type' => 'translate'
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
            0 => [
                'name' => $this->translate('Add a role'),
                'controller' => 'acl-administration',
                'action' => 'add-role',
                'check_acl' => true
            ]
        ],
        'multiple_actions' => [
            0 => [
                'name' => $this->translate('Delete selected'),
                'controller' => 'acl-administration',
                'action' => 'delete-roles',
                'check_acl' => true,
                'confirm' => $this->translate('Selected roles will be deleted. Are you sure?')
            ]
        ],
        'single_actions' => [
            0 => [
                'name' => $this->translate('Edit the role'),
                'controller' => 'acl-administration',
                'action' => 'edit-role',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/edit_action.png', 'image')
            ],
            1 => [
                'name' => $this->translate('Browse resources'),
                'controller' => 'acl-administration',
                'action' => 'browse-resources',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/browse_action.png', 'image', 'acl')
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'acl-roles',
        'multiple_actions' => [
            'items_name' => 'roles[]'
        ]
    ],
    'actions_extra_check' => [
        'multiple_actions' => [
            'system_items' => [
                'param' => 'type',
                'condition' =>  'return "__value__" == "' . AclBaseModel::ROLE_TYPE_SYSTEM . '" ? false : true;'
            ]
        ],
        'single_actions' => [
            'edit-role' => [
                0 => [
                    'param' => 'type',
                    'condition' =>  'return "__value__" == "' . AclBaseModel::ROLE_TYPE_SYSTEM . '" ? false : true;'
                ]
            ],
            'browse-resources' => [
                0 => [
                    'param' => 'id',
                    'condition' =>  'return "__value__" == "' . AclBaseModel::DEFAULT_ROLE_ADMIN . '" ? false : true;'
                ]
            ]
        ]
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Roles'),
    'body' => $this->content
]) ?>