<?php $this->declareVars('subPageTitle', 'parentPageTitle') ?>
<?php $this->parentPageTitle = $this->translate($this->resourceSettings['role_name']) ?>
<?php $this->subPageTitle = $this->translate($this->resourceSettings['resource_description']) ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>
<?php $this->headTitle($this->translate('List of roles')) ?>

<!-- render a header -->
<?php echo $this->render('acl/acl-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of roles'),
            'controller' => 'acl-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_resources' => [
            'name' => $this->parentPageTitle,
            'controller' => 'acl-administration',
            'action' => 'browse-resources',
            'check_acl' => true,
            'params' => [
                'slug' => $this->resourceSettings['role']
            ]
        ],
        'resource_settings' => [
            'name' => $this->subPageTitle,
            'controller' => 'acl-administration',
            'action' => 'resource-settings',
            'check_acl' => true
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('General info'),
    'body' => $this->partial('partial/form', ['form' => $this->aclResourceSettingsForm])
]) ?>