<?php use Acl\Model\AclBase as AclBaseModel; ?>

<?php $this->declareVars('extraActions', 'subPageTitle', 'parentPageTitle') ?>
<?php $this->parentPageTitle = $this->translate($this->resource_settings['role_name']) ?>
<?php $this->subPageTitle = $this->translate($this->resource_settings['resource_description']) ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>
<?php $this->headTitle($this->translate('List of roles')) ?>

<!-- render a header -->
<?php echo $this->render('acl/acl-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of roles'),
            'controller' => 'acl-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_resources' => [
            'name' => $this->parentPageTitle,
            'controller' => 'acl-administration',
            'action' => 'browse-resources',
            'check_acl' => true,
            'params' => [
                'slug' => $this->resource_settings['role']
            ]
        ],
        'resource_settings' => [
            'name' => $this->subPageTitle,
            'controller' => 'acl-administration',
            'action' => 'resource-settings',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'hide_action' => AclBaseModel::ROLE_TYPE_SYSTEM == $this->resource_settings['role_type'],
        'controller' => 'acl-administration',
        'action' => 'edit-role',
        'params' => [
            'slug' => $this->resource_settings['role']
        ],
        'name' => $this->translate('Edit the role'),
        'check_acl' => true
    ],
    [
        'hide_action' => AclBaseModel::ROLE_TYPE_SYSTEM == $this->resource_settings['role_type'],
        'controller' => 'acl-administration',
        'action' => 'delete-roles',
        'name' => $this->translate('Delete the role'),
        'check_acl' => true,
        'confirm' => $this->translate('Role will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'roles' : [{$this->resource_settings['role']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'acl-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'acl-administration',
        'action' => 'add-role',
        'name' => $this->translate('Add a role'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('General info'),
                'body' => $this->partial('partial/form', ['form' => $this->acl_form])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('General info'),
                'body' => $this->partial('partial/form', ['form' => $this->acl_form])
            ]) ?>
        </div>
    <?php endif ?>
</div>