<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Delete your account') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<h1><?php echo $this->escapeHtml($this->pageTitle); ?></h1>

<!-- render a form -->
<?php echo $this->partial('partial/form', array(
    'form' => $this->deleteForm,
    'controller' => 'user',
    'action' => 'delete',
    'categoriesAlwaysOpened' => true
)); ?>