<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Have you forgotten your password or nickname?') ?>
<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'home' => array(
            'name' => $this->translate('Home'),
            'controller' => 'Home',
            'action' => 'index',
            'check_acl' => false
        ),
        'user_forgot' => array(
            'name' => $this->pageTitle,
            'controller' => 'user',
            'action' => 'forgot',
            'check_acl' => false
        )
    )
)) ?>

<!-- render a form -->
<?php echo $this->partial('partial/form', array(
    'form' => $this->forgotForm,
    'controller' => 'user',
    'action' => 'forgot',
    'categoriesAlwaysOpened' => true
)); ?>