<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Login') ?>
<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'home' => array(
            'name' => $this->translate('Home'),
            'controller' => 'Home',
            'action' => 'index',
            'check_acl' => false
        ),
        'user_login' => array(
            'name' => $this->pageTitle,
            'controller' => 'user',
            'action' => 'login',
            'check_acl' => false
        )
    )
)) ?>

<?php echo $this->partial('partial/form', array(
    'form' => $this->loginForm,
    'controller' => 'user',
    'action' => 'login'
)); ?>
<br />
<br />
<a href="<?php echo  $this->url('application', array('controller' => 'user', 'action' => 'forgot')) ?>"><?php echo $this->escapeHtml($this->translate('Can\'t access your account?')) ?></a>

<?php if ((int) $this->getSetting('user_allow_register')): ?>
    <br />
    <a href="<?php echo  $this->url('application', array('controller' => 'user', 'action' => 'register')) ?>"><?php echo $this->escapeHtml($this->translate('Create a new account')) ?></a>
<?php endif; ?>