<?php $this->headTitle($this->translate('Modules')) ?>

<div class="page-header">
  <h1>
    <img src="<?php  echo $this->asset('icons/modules.png', 'images') ?>" alt="<?php echo $this->escapeHtmlAttr($this->translate('Modules')) ?>" />    
    <?php echo $this->translate('Modules') ?>
  </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
  $this->baseTabs = array(
      'list' => array(
      'name' => $this->translate('List of modules'),
      'controller' => 'modules_administration',
      'action' => 'index',
      'check_acl' => true
    ) 
  );
?>