<?php $this->declareVars('pageTitle') ?>
<?php $this->pageTitle = $this->translate('Payments') ?>

<?php $this->headTitle($this->escapeHtml($this->pageTitle)) ?>

<div class="page-header">
  <h1>
    <img src="<?php  echo $this->asset('icon/cart.png', 'image', 'payment') ?>" alt="<?php echo $this->escapeHtmlAttr($this->pageTitle) ?>" />    
    <?php echo $this->escapeHtml($this->pageTitle) ?>
  </h1>
</div>

<?php $this->declareVars('baseTabs') ?>

<?php
    $this->baseTabs = array(
        'list' => array(
            'name' => $this->translate('List of transactions'),
            'controller' => 'payments-administration',
            'action' => 'list',
            'check_acl' => true
        ),
        'currencies' => array(
            'name' => $this->translate('Currencies'),
            'controller' => 'payments-administration',
            'action' => 'currencies',
            'check_acl' => true
        ),
        'cupons' => array(
            'name' => $this->translate('Discount coupons'),
            'controller' => 'payments-administration',
            'action' => 'coupons',
            'check_acl' => true
        )
    );
?>