<?php $this->declareVars('subPageTitle', 'parentPageTitle') ?>

<?php $this->subPageTitle = $this->translate('Edit the currency') ?>
<?php $this->parentPageTitle = $this->translate('Currencies') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'currencies' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'currencies' => array(
            'name' => $this->parentPageTitle,
            'controller' => 'payments-administration',
            'action' => 'currencies',
            'check_acl' => true
        ),
        'add_currency' => array(
            'name' => $this->subPageTitle,
            'controller' => 'payments-administration',
            'action' => 'edit-currency',
            'check_acl' => true
        )
    )
)) ?>

<!-- render a form -->
<?php echo $this->partial('partial/form', array(
    'form' => $this->currencyForm,
    'controller' => 'payments-administration',
    'action' => 'edit-currency',
    'params' => array(
        'slug' => $this->currency['id']
    )
)); ?>