<?php $this->declareVars('subPageTitle', 'parentPageTitle') ?>

<?php $this->subPageTitle = $this->translate('View the transaction\'s details') ?>
<?php $this->parentPageTitle = $this->translate('List of transactions') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->transaction['slug']) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->parentPageTitle,
            'controller' => 'payments-administration',
            'action' => 'list',
            'check_acl' => true
        ),
        'view_details' => array(
            'name' => $this->transaction['slug'] . ' - ' . $this->subPageTitle,
            'controller' => 'payments-administration',
            'action' => 'view-transaction-details',
            'check_acl' => true
        )
    ) 
)) ?>

<!-- render a table with values -->
<?php echo $this->partial('partial/table', array(
    'headers' => array(
    ),
    'list' => array(
        'name' => array(
            $this->translate('First Name'),
            $this->transaction['first_name']
        ),
        'surname' => array(
            $this->translate('Last Name'),
            $this->transaction['last_name']
        ),
        'user_registered' => array(
            $this->translate('User registered'),
            $this->booleanValue($this->transaction['user_id'])
        ),
        'email' => array(
            $this->translate('Email'),
            $this->transaction['email']
        ),
        'phone' => array(
            $this->translate('Phone'),
            $this->transaction['phone']
        ),
        'address' => array(
            $this->translate('Address'),
            $this->transaction['address']
        ),
        'date' => array(
            $this->translate('Date'),
            $this->date($this->transaction['date'], array('type' => 'date'))
        ),
        'paid' => array(
            $this->translate('Paid'),
            $this->booleanValue($this->transaction['paid'])
        ),
        'currency' => array(
            $this->translate('Currency'),
            $this->transaction['currency_code']
        ),
        'payment_type' => array(
            $this->translate('Payment type'),
            (
                $this->transaction['payment_description']
                    ? $this->translate($this->transaction['payment_description'])
                    : ''
            )
        ),
        'discount' => array(
            $this->translate('Discount'),
            (
                $this->transaction['discount_cupon']
                    ? $this->transaction['discount_cupon'] . '%'
                    : ''
            )
        ),
        'amount' => array(
            $this->translate('Total amount'),
            $this->costFormat(array(
                'cost' => $this->transaction['amount'],
                'currency' => $this->transaction['currency_code']
            ))
        ),
        'comments' => array(
            $this->translate('Comments'),
            $this->transaction['comments']
        )
    ) 
)) ?>