<?php $this->declareVars('subPageTitle', 'parentPageTitle') ?>

<?php $this->subPageTitle = $this->translate('View the transaction\'s details') ?>
<?php $this->parentPageTitle = $this->translate('List of transactions') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->transaction['slug']) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->parentPageTitle,
            'controller' => 'payments-administration',
            'action' => 'list',
            'check_acl' => true
        ),
        'view_details' => array(
            'name' => $this->transaction['slug'] . ' - ' . $this->subPageTitle,
            'controller' => 'payments-administration',
            'action' => 'view-transaction-details',
            'check_acl' => true
        )
    ) 
)) ?>

<!-- render a table with values -->
<?php echo $this->partial('partial/table', array(
    'headers' => array(
    ),
    'list' => array(
        'name' => array(
            'first_name' => 'First Name',
            'name_value' => $this->transaction['first_name']
        ),
        'surname' => array(
            'surname' => 'Last Name',
            'surname_value' => $this->transaction['last_name']
        ),
        'user_registered' => array(
            'user_registered' => 'User registered',
            'user_registered_value' => $this->transaction['user_id']
        ),
        'email' => array(
            'email' => 'Email',
            'email_value' => $this->transaction['email']
        ),
        'phone' => array(
            'phone' => 'Phone',
            'phone_value' => $this->transaction['phone']
        ),
        'address' => array(
            'address' => 'Address',
            'address_value' => $this->transaction['address']
        ),
        'date' => array(
            'date' => 'Date',
            'date_value' => $this->transaction['date']
        ),
        'paid' => array(
            'paid' => 'Paid',
            'paid_value' => $this->transaction['paid']
        ),
        'currency' => array(
            'currency' => 'Currency',
            'currency_value' => $this->transaction['currency_code']
        ),
        'payment_type' => array(
            'payment_type' => 'Payment type',
            'payment_type_value' => ($this->transaction['payment_description'] ? $this->translate($this->transaction['payment_description']) : '')
        ),
        'discount' => array(
            'discount' => 'Discount',
            'discount_value' => ($this->transaction['discount_cupon'] ? $this->transaction['discount_cupon'] . '%' : '')
        ),
        'amount' => array(
            'total_amount' => 'Total amount',
            'total_amount_value' => $this->costFormat(array(
                'cost' => $this->transaction['amount'],
                'currency' => $this->transaction['currency_code']
            ))
        ),
        'comments' => array(
            'comments' => 'Comments',
            'comments_value' => $this->transaction['comments']
        )
    ),
    'helpers' => array(
        'first_name' => 'translate',
        'surname' => 'translate',
        'user_registered' => 'translate',
        'user_registered_value' => 'booleanValue',
        'email' => 'translate',
        'phone' => 'translate',
        'address' => 'translate',
        'date' => 'translate',
        'date_value' => 'date',
        'paid' => 'translate',
        'paid_value' => 'booleanValue',
        'currency' => 'translate',
        'payment_type' => 'translate',
        'discount' => 'translate',
        'total_amount' => 'translate',
        'comments' => 'translate'
    )    
)) ?>