<?php $this->declareVars('userEditUrl') ?>

<div class="thumbnail">
    <img alt="<?php echo $this->escapeHtmlAttr($user['nick_name']) ?>" src="<?php echo $this->escapeHtmlAttr($this->userAvatarUrl($user['avatar'], false)) ?>" />
</div>
<div class="list-group">
    <div class="list-group-item">
        <h4 class="list-group-item-heading"><?php echo $this->translate('Role') ?></h4>
        <p><?php echo $this->translate($user['role_name']) ?></p>
    </div>
    <div class="list-group-item">
        <h4 class="list-group-item-heading"><?php echo $this->translate('Email') ?></h4>
        <p><?php echo $this->escapeHtml($user['email']) ?></p>
        <?php if (false !== ($this->userEditUrl = $this->pageUrl('user-edit'))) : ?>
            <p>    
                <a href="<?php echo  $this->url('page', ['page_name' => $this->userEditUrl], ['force_canonical' => true]) ?>">
                    <?php echo $this->translate('Edit account') ?>
                </a>
            </p>    
        <?php endif ?>
    </div>
    <?php if ($user['time_zone_name']): ?>
        <div class="list-group-item">
            <h4 class="list-group-item-heading"><?php echo $this->translate('Time zone') ?></h4>
            <p><?php echo $this->escapeHtml($user['time_zone_name']) ?></p>
        </div>
    <?php endif ?>
</div>
