<?php echo $this->partial('partial/form', [
    'form' => $this->loginForm,
]) ?>

<?php if (false !== $this->pageUrl('forgot')): ?>
    <br />
    <a href="<?php echo  $this->url('page', array('page_name' => $this->pageUrl('forgot'))) ?>">
        <?php echo $this->translate('Can\'t access your account?') ?>
    </a>
<?php endif ?>

<?php if ((int) $this->applicationSetting('user_allow_register') && false !== $this->pageUrl('register')): ?>
    <br />
    <a href="<?php echo  $this->url('page', array('page_name' => $this->pageUrl('register'))) ?>">
        <?php echo $this->translate('Create a new account') ?>
    </a>
<?php endif ?>