<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FileManager\Test\FileManagerBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
    'FileManager\Test\Event\DeleteUserTest'                      => __DIR__ . '/test/FileManager/src/FileManager/Event/DeleteUserTest.php',
    'FileMangager\Test\Model\BaseTest'                           => __DIR__ . '/test/FileManager/src/FileManager/Model/BaseTest.php',
    'FileManager\Module'                                         => __DIR__ . '/Module.php',
    'FileManager\Form\FileManagerDirectory'                      => __DIR__ . '/src/FileManager/Form/FileManagerDirectory.php',
    'FileManager\Form\FileManagerFileFilter'                     => __DIR__ . '/src/FileManager/Form/FileManagerFileFilter.php',
    'FileManager\Form\FileManagerFile'                           => __DIR__ . '/src/FileManager/Form/FileManagerFile.php',
    'FileManager\Form\FileManagerEdit'                           => __DIR__ . '/src/FileManager/Form/FileManagerEdit.php',
    'FileManager\Controller\FileManagerAdministrationController' => __DIR__ . '/src/FileManager/Controller/FileManagerAdministrationController.php',
    'FileManager\Controller\FileManagerEmbeddedController'       => __DIR__ . '/src/FileManager/Controller/FileManagerEmbeddedController.php',
    'FileManager\Controller\FileManagerBaseController'           => __DIR__ . '/src/FileManager/Controller/FileManagerBaseController.php',
    'FileManager\View\Helper\FileManagerFileUrl'                 => __DIR__ . '/src/FileManager/View/Helper/FileManagerFileUrl.php',
    'FileManager\View\Helper\FileManagerBaseFileUrl'             => __DIR__ . '/src/FileManager/View/Helper/FileManagerBaseFileUrl.php',
    'FileManager\View\Helper\FileManagerDirectoryTree'           => __DIR__ . '/src/FileManager/View/Helper/FileManagerDirectoryTree.php',
    'FileManager\Exception\FileManagerException'                 => __DIR__ . '/src/FileManager/Exception/FileManagerException.php',
    'FileManager\Event\FileManagerEvent'                         => __DIR__ . '/src/FileManager/Event/FileManagerEvent.php',
    'FileManager\Model\FileManagerBase'                          => __DIR__ . '/src/FileManager/Model/FileManagerBase.php',
);
