<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'FileManager\Test\FileManagerBootstrap'                      => __DIR__ . '/test/Bootstrap.php',
  'FileMangager\Test\Model\BaseTest'                           => __DIR__ . '/test/FileManager/src/FileManager/Model/BaseTest.php',
  'FileManager\Module'                                         => __DIR__ . '/Module.php',
  'FileManager\Form\FileFilter'                                => __DIR__ . '/src/FileManager/Form/FileFilter.php',
  'FileManager\Form\Directory'                                 => __DIR__ . '/src/FileManager/Form/Directory.php',
  'FileManager\Form\Edit'                                      => __DIR__ . '/src/FileManager/Form/Edit.php',
  'FileManager\Form\File'                                      => __DIR__ . '/src/FileManager/Form/File.php',
  'FileManager\Controller\FileManagerAdministrationController' => __DIR__ . '/src/FileManager/Controller/FileManagerAdministrationController.php',
  'FileManager\Controller\FileManagerEmbeddedController'       => __DIR__ . '/src/FileManager/Controller/FileManagerEmbeddedController.php',
  'FileManager\Controller\FileManagerBaseController'           => __DIR__ . '/src/FileManager/Controller/FileManagerBaseController.php',
  'FileManager\View\Helper\FileUrl'                            => __DIR__ . '/src/FileManager/View/Helper/FileUrl.php',
  'FileManager\View\Helper\BaseFileUrl'                        => __DIR__ . '/src/FileManager/View/Helper/BaseFileUrl.php',
  'FileManager\View\Helper\FileManagerDirectoryTree'           => __DIR__ . '/src/FileManager/View/Helper/FileManagerDirectoryTree.php',
  'FileManager\Event\Event'                                    => __DIR__ . '/src/FileManager/Event/Event.php',
  'FileManager\Model\Base'                                     => __DIR__ . '/src/FileManager/Model/Base.php',
);
