<!-- render a list of files -->
<?php if ($this->paginator === false) : ?>
    <div class="alert alert-danger">
        <?php echo $this->translate('Directory not exists') ?>
    </div>
<?php else: ?>
    <!-- render a data grid -->
    <?php echo $this->partial('partial/data_grid', array(
        'controller' => $this->currentRoute()->getController(),
        'action' => $this->currentRoute()->getAction(),
        'queries' => array(
            'path' => $this->path
        ),
        'order_by' => $this->order_by,
        'order_type' => $this->order_type,
        'per_page' => $this->per_page,
        'default_order' => 'name',
        'default_order_type' => 'desc',
        'filter_form' => $this->filter_form,
        'headers' => array(
            0 => array(
                'title' => $this->translate('Name'),
                'order_name' => 'name'
            ),
            1 => array(
                'title' => $this->translate('Type'),
                'order_name' => 'type'
            ),
            2 => array(
                'title' => $this->translate('Modified date'),
                'order_name' => 'date'
            ),
            3 => array(
                'title' => $this->translate('File size'),
                'order_name' => 'size'
            )
        ),
        'paginator' => $this->paginator,
        'skipped_fields' => array(
        ),
        'helpers' => array(
            'size' => 'fileSize',
            'name' => 'fileUrl',
            'type' => 'booleanValue',
            'date' => 'date'
        ),
        'helpers_options' => array(
            'name' => array(
                'path' => $this->path,
                'filters' => $this->filters
            ),
            'type' => array(
                'true_string' => $this->translate('Directory'),
                'false_string' => $this->translate('File')
            )
        ),
        'actions' => array (
            'regular_actions' => array(
                0 => array(
                    'name' => $this->translate('Add a directory'),
                    'controller' => $this->currentRoute()->getController(),
                    'action' => 'add-directory',
                     'queries' => array(
                        'path' => $this->path
                     ),
                    'check_acl' => true
                ),
                1 => array(
                    'name' => $this->translate('Add a file'),
                    'controller' => $this->currentRoute()->getController(),
                    'action' => 'add-file',
                     'queries' => array(
                        'path' => $this->path
                     ),
                    'check_acl' => true
                )
            ),
            'multiple_actions' => array(
                0 => array(
                    'name' => $this->translate('Delete selected'),
                    'controller' => $this->currentRoute()->getController(),
                    'action' => 'delete',
                    'queries' => array(
                        'path' => $this->path
                     ),
                    'check_acl' => true,
                    'confirm' => $this->translate('Selected files and dirs will be deleted. Are you sure?')
                ),
            )
        ),
        'actions_options' => array(
            'action_identity' => 'name',
            'form_name' => 'files',
            'multiple_actions' => array(
                'items_name' => 'files[]'
            )
        ),
        'actions_extra_check' => array(
        )
    )) ?>    
<?php endif; ?>