<!-- include needed js and css files -->
<?php $this->headScript()->appendFile($this->asset('jquery.treeview.js')) ?>
<?php $this->headLink()->appendStylesheet($this->asset(($this->localization()->isCurrentLanguageLtr()
        ? 'jquery.treeview.css'
        : 'jquery.treeview.rtl.css'), 'css')) ?>

<?php $this->headLink()->appendStylesheet($this->asset('main.css', 'css', 'filemanager')) ?>

<?php $this->declareVars('directoriesTreeId') ?>
<?php $this->directoriesTreeId = 'directories-tree' ?>

<!-- files manager wrapper -->
<div class="row" id="files-manager-wrapper">
    <div class="col-md-3">
        <div id="directories-tree-wrapper">
            <?php echo $this->filesManagerDirectoriesTree($this->userDirectories, $this->directoriesTreeId, $this->path, $this->filters) ?>
        </div>
    </div>
    <div class="col-md-9">
        <div id="action-wrapper">
            <?php echo $this->action ?>
        </div>
    </div>
</div>

<?php $this->inlineScript()->captureStart() ?>
    $("#<?php echo $this->directoriesTreeId ?>").treeview({});
<?php $this->inlineScript()->captureEnd() ?>