<?php
// Generated by ZF2's ./bin/classmap_generator.php
return [
    'XmlRpc\Utility\XmlRpcCache'           => __DIR__ . '/src/XmlRpc/Utility/XmlRpcCache.php',
    'XmlRpc\Model\XmlRpcBase'              => __DIR__ . '/src/XmlRpc/Model/XmlRpcBase.php',
    'XmlRpc\Model\XmlRpc'                  => __DIR__ . '/src/XmlRpc/Model/XmlRpc.php',
    'XmlRpc\Controller\XmlRpcController'   => __DIR__ . '/src/XmlRpc/Controller/XmlRpcController.php',
    'XmlRpc\Exception\XmlRpcException'     => __DIR__ . '/src/XmlRpc/Exception/XmlRpcException.php',
    'XmlRpc\Exception\XmlRpcActionDenied'  => __DIR__ . '/src/XmlRpc/Exception/XmlRpcActionDenied.php',
    'XmlRpc\Handler\XmlRpcAbstractHandler' => __DIR__ . '/src/XmlRpc/Handler/XmlRpcAbstractHandler.php',
    'XmlRpc\Module'                        => __DIR__ . '/Module.php',
    'XmlRpc\Test\XmlRpcBootstrap'          => __DIR__ . '/test/Bootstrap.php',
];
