<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'XmlRpc\Test\XmlRpcBootstrap'                 => __DIR__ . '/test/Bootstrap.php',
    'XmlRpc\Test\Controller\XmlRpcControllerTest' => __DIR__ . '/test/XmlRpc/src/XmlRpc/Controller/XmlRpcControllerTest.php',
    'XmlRpc\Module'                               => __DIR__ . '/Module.php',
    'XmlRpc\Controller\XmlRpcController'          => __DIR__ . '/src/XmlRpc/Controller/XmlRpcController.php',
    'XmlRpc\Exception\XmlRpcActionDenied'         => __DIR__ . '/src/XmlRpc/Exception/XmlRpcActionDenied.php',
    'XmlRpc\Model\XmlRpc'                         => __DIR__ . '/src/XmlRpc/Model/XmlRpc.php',
    'XmlRpc\Model\Base'                           => __DIR__ . '/src/XmlRpc/Model/Base.php',
);
