<div class="modal fade" id="popup-acl-role-window">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Add the item to the shopping cart') ?></h4>
            </div>
            <div class="modal-body">
                    asdsadsadsadsadasdsada
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
            </div>
        </div>
    </div>
</div>
