<?php use Zend\Form\Element ?>

<div class="preview-file-wrapper">
    <div class="row">
        <div class="col-sm-6 col-md-5">
            <a target="_blank" href="<?php echo $this->escapeHtmlAttr($this->file_url)?>"><?php echo $this->escapeHtml($this->file_url) ?></a>
        </div>
    </div>
    <?php if ($this->delete_option): ?>
        <p class="help-block">
            <label>
                <?php
                    $deletePreview = new Element\Checkbox($this->name . '_delete');
                    $deletePreview->setUseHiddenElement(false);
                    echo $this->formCheckbox($deletePreview);                    
                ?>
                <?php echo $this->escapeHtml($this->translate('Delete file')) ?>
            </label>
        </p>
    <?php endif; ?>
</div>
