<?php if (count($this->items) > 1): ?>
    <?php $this->declareVars('uncategorized', 'content', 'index', 'randPrefix') ?>
    <?php $this->uncategorized = null ?>
    <div class="panel-group" id="<?php echo $this->escapeHtmlAttr($this->name) ?>">
        <?php foreach ($this->items as $category => $content) : ?>
            <?php if (null == $category): ?>
                <?php $this->uncategorized .= $content; continue; ?>
            <?php endif; ?>
            <?php $this->index++ ?>
            <?php $this->randPrefix = $this->escapeHtmlAttr($this->applicationRandId()) ?>
            <div class="panel panel-default panel-accordion">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#<?php echo $this->escapeHtmlAttr($this->name) ?>" href="#<?php echo $this->randPrefix ?>_collapse-<?php echo $this->escapeHtmlAttr($this->index) ?>">
                            <?php echo $this->translate($category) ?>
                        </a>
                    </h4>
                </div>
                <div id="<?php echo $this->randPrefix ?>_collapse-<?php echo $this->escapeHtmlAttr($this->index) ?>" class="panel-collapse collapse <?php if (($this->index == 1 && ! (array) $this->openCategories) || (in_array($category, (array) $this->openCategories))): ?>in<?php else: ?>collapse<?php endif ?>">
                    <div class="panel-body">
                        <?php echo $content ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <?php echo $this->uncategorized ?>
    </div>
<?php else: ?>
    <?php echo current($this->items) ?>
<?php endif ?>