<?php use Page\Model\Page as PageModel ?>
<?php $this->declareVars('pageUrl', 'pageTitle') ?>

<?php if (count($this->breadcrumb) != 1): ?>
    <ol class="breadcrumb">
        <?php foreach($this->breadcrumb as $page) : ?>
            <?php $this->pageUrl  .= $page['slug'] ?>
            <?php $this->pageTitle = $page['type'] == PageModel::PAGE_TYPE_SYSTEM ? $this->translate($page['title']) : $this->escapeHtml($page['title']) ?>
            <li>
                <?php if ($this->page['slug'] == $page['slug']) : ?>
                    <?php echo $this->pageTitle ?>
                <?php else: ?>
                    <a href="<?php echo $this->url('page', array('page_name' => $this->pageUrl), array('force_canonical' => true)) ?>">
                        <?php echo $this->pageTitle ?>
                    </a>
                <?php endif ?>
            </li>
            <?php $this->pageUrl .= '/' ?>
        <?php endforeach ?>
    </ol>
<?php endif ?>