<?php use Application\Utility\ApplicationPagination as PaginationUtility ?>

<?php $this->declareVars('filterFormParams', 'perPageRanges', 'paginationCount', 'unitExtraParams', 'routeParams' , 'routeQueries', 'defaultRoute', 'widgetParams') ?>

<?php 
    // init pagination params
    $this->paginationCount = $this->paginator ? $this->paginator->count() : 0;

    $this->routeParams = !empty($this->route_params) && is_array($this->route_params) 
        ? array_merge($this->applicationRoute()->getAllDefaultRouteParams(), $this->route_params)
        : $this->applicationRoute()->getAllDefaultRouteParams();

    $this->routeQueries = !empty($this->route_queries) && is_array($this->route_queries) 
        ? array_merge($this->applicationRoute()->getQuery(), $this->route_queries)
        : $this->applicationRoute()->getQuery();

    // clear widget params from url
    $this->routeQueries = array_merge($this->routeQueries, [
        'widget_connection' => null,
        'widget_position' => null,
        '_' => null
    ]);

    $this->defaultRoute = !empty($this->route) ? $this->route : 'page';

    // init a per page changer
    $this->per_page = PaginationUtility::processPerPage($this->per_page);
    $this->perPageRanges = PaginationUtility::getPerPageRanges();

    // init data unit params
    $this->unitExtraParams = !empty($this->unit_params) && is_array($this->unit_params) ? $this->unit_params : [];

    // process filter form params
    if ($this->filter_form) {
        $this->filterFormParams = $this->routeQueries;
        $this->filterFormParams = array_merge($this->filterFormParams, ['form_name' => null]);

        foreach($this->filter_form as $element) {
            if (!empty($this->filterFormParams[$element->getName()])) {
                $this->filterFormParams = array_merge($this->filterFormParams, [$element->getName() => null]);
            }
        }

        // set the filter form url
        $this->filter_form->setAttribute('action', $this->url($this->
                defaultRoute, $this->routeParams, ['force_canonical' => true, 'query' => $this->filterFormParams]));
    }
?>

<div class="data-list">
    <?php if (($this->filter_form || $this->paginator_per_page_show || ($this->paginator_order_list_show && !empty($this->paginator_order_list)))) : ?>
        <ul class="nav nav-pills">
            <?php if ($this->filter_form): ?>
                <li class="dropdown <?php if ($this->localization()->isCurrentLanguageLtr()) : ?>pull-left<?php else: ?>pull-right<?php endif ?><?php if (!$this->filter_form->isValid()) : ?> open<?php endif ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo $this->translate('Filter') ?>
                        <span class="caret"></span>
                    </a>
                    <div class="dropdown-menu">
                        <div class="filter-form">
                            <?php echo $this->partial('partial/form', [
                                'form' => $this->filter_form
                            ]) ?>
                        </div>
                    </div>
                </li>
            <?php endif ?>
            <?php if ($this->paginationCount && $this->paginator_per_page_show && $this->paginationCount && count($this->perPageRanges) > 1) : ?>
                <li class="dropdown <?php if ($this->localization()->isCurrentLanguageLtr()) : ?>pull-right<?php else: ?>pull-left<?php endif; ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo $this->translate('Per page') ?> - <?php echo $this->per_page ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach ($this->perPageRanges as $perPage) : ?>
                            <li <?php if ($this->per_page == $perPage) : ?>class="disabled"<?php endif; ?>>
                                <?php if (!$this->paginator_per_page_query): ?>
                                    <a href="<?php echo $this->url($this->defaultRoute, array_merge($this->routeParams, ['per_page' => $perPage]), ['force_canonical' => true, 'query' => $this->routeQueries]) ?>">
                                        <?php echo $perPage ?>
                                    </a>
                                <?php else: ?>
                                    <a href="<?php echo $this->url($this->defaultRoute, $this->routeParams, ['force_canonical' => true, 'query' => [$this->paginator_per_page_query => $perPage] + $this->routeQueries]) ?>">
                                        <?php echo $perPage ?>
                                    </a>
                                <?php endif ?>
                            </li>
                        <?php endforeach ?>
                    </ul>
                </li>
            <?php endif ?>

            <?php if ($this->paginationCount && $this->paginator_order_list_show && !empty($this->paginator_order_list)) : ?>
                <li class="dropdown <?php if ($this->localization()->isCurrentLanguageLtr()) : ?>pull-right<?php else: ?>pull-left<?php endif ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo $this->translate('Order') ?><?php if (!empty($this->orderList[$this->order_by])) : ?> - <?php echo $this->translate($this->orderList[$this->order_by]) ?><?php endif ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach ($this->paginator_order_list as $order => $orderTitle) : ?>
                            <li <?php if ($this->order_by == $order) : ?>class="disabled"<?php endif ?>>
                                <?php if (!$this->paginator_order_by_query): ?>
                                    <a href="<?php echo $this->url($this->defaultRoute, array_merge($this->routeParams, ['order_by' => $order]), ['force_canonical' => true, 'query' => $this->routeQueries]) ?>">
                                        <?php echo $this->translate($orderTitle) ?>
                                    </a>
                                <?php else: ?>
                                    <a href="<?php echo $this->url($this->defaultRoute, $this->routeParams, ['force_canonical' => true, 'query' => [$this->paginator_order_by_query => $order] + $this->routeQueries]) ?>">
                                        <?php echo $this->translate($orderTitle) ?>
                                    </a>
                                <?php endif ?>
                            </li>
                        <?php endforeach ?>
                        <li class="divider"></li>
                        <li <?php if ($this->order_type == 'asc') : ?>class="disabled"<?php endif ?>>
                            <?php if (!$this->paginator_order_type_query): ?>
                                <a href="<?php echo $this->url($this->defaultRoute, array_merge($this->routeParams, ['order_type' => 'asc']), ['force_canonical' => true, 'query' => $this->routeQueries]) ?>">
                                    <?php echo $this->translate('Ascending') ?>
                                </a>
                            <?php else: ?>
                                <a href="<?php echo $this->url($this->defaultRoute, $this->routeParams, ['force_canonical' => true, 'query' => [$this->paginator_order_type_query => 'asc'] + $this->routeQueries]) ?>">
                                    <?php echo $this->translate('Ascending') ?>
                                </a>
                            <?php endif ?>
                        </li>
                        <li <?php if ($this->order_type == 'desc') : ?>class="disabled"<?php endif ?>>
                            <?php if (!$this->paginator_order_type_query): ?>
                                <a href="<?php echo $this->url($this->defaultRoute, array_merge($this->routeParams, ['order_type' => 'desc']), ['force_canonical' => true, 'query' => $this->routeQueries]) ?>">
                                    <?php echo $this->translate('Descending') ?>
                                </a>
                            <?php else: ?>
                                <a href="<?php echo $this->url($this->defaultRoute, $this->routeParams, ['force_canonical' => true, 'query' => [$this->paginator_order_type_query => 'desc'] + $this->routeQueries]) ?>">
                                    <?php echo $this->translate('Descending') ?>
                                </a>
                            <?php endif ?>
                        </li>
                    </ul>
                </li>
            <?php endif ?>
        </ul>
    <?php endif ?>

    <?php if ($this->paginationCount): ?>
        <?php foreach ($this->paginator as $data) : ?>
            <?php echo $this->partial($this->unit, array_merge(['data' => $data], $this->unitExtraParams)) ?>
        <?php endforeach ?>

        <?php
            echo $this->paginationControl($this->paginator, 'Sliding', 'partial/slide-paginator', [
                'route'   => $this->defaultRoute,
                'params'  => $this->routeParams,
                'queries' => $this->routeQueries,
                'paginator_page_query' => $this->paginator_page_query
            ])
        ?>
    <?php else: ?>
        <div class="alert alert-warning">
            <?php echo $this->translate('Nothing found') ?>
        </div>
    <?php endif ?>
</div>

<?php if (($this->filter_form || $this->paginationCount) && isset($this->ajax['wrapper_id'], $this->ajax['widget_connection'], $this->ajax['widget_position'])) : ?>
    <script type="text/javascript">
        $(document).ready(function () {

            var wrapperId           = '<?php echo $this->escapeJs($this->ajax['wrapper_id']) ?>';
            var widgetConnectionId  = '<?php echo (int) $this->ajax['widget_connection'] ?>';
            var widgetPosition      = '<?php echo $this->escapeJs($this->ajax['widget_position']) ?>';

            <?php if ($this->filter_form): ?>
                $('#<?php echo $this->escapeJs($this->ajax['wrapper_id']) ?>').find("[name='<?php echo $this->escapeJs($this->filter_form->getName()) ?>']").submit(function(event) {
                    event.preventDefault();

                    // get data
                    dataListQuery(wrapperId, $(this).attr('action'), widgetConnectionId, widgetPosition, $(this).serialize());
                });
            <?php endif ?>

            <?php if ($this->paginationCount): ?>
                // listen for all clicks
                $('#<?php echo $this->escapeJs($this->ajax['wrapper_id']) ?>').find('.data-list .dropdown-menu a, .data-list ul.pagination a').bind('click', function(e){
                    e.preventDefault();

                    // get data
                    dataListQuery(wrapperId, $(this).attr('href'), widgetConnectionId, widgetPosition);
                });
            <?php endif ?>
        });
    </script>
<?php endif ?>