<?php use Application\Utility\Pagination as PaginationUtility ?>

<?php
    $this->declareVars('paginationCount', 'perPageRanges', 'baseUrlParams');

    // init pagination
    $this->paginationCount = $this->paginator
        ? $this->paginator->count()
        : 0;

    // init a per page changer
    $this->per_page = PaginationUtility::processPerPage($this->per_page);
    $this->perPageRanges = PaginationUtility::getPerPageRanges();

    // base url params
    $this->baseUrlParams = array(
        'controller' => $this->controller,
        'action' => $this->action,
        'per_page' => $this->per_page,
        'order_by' => $this->order_by,
        'order_type' => $this->order_type,
        'slug' => $this->slug
    );
?>

<div class="data-list">
    <?php if ($this->showPerPage || $this->orderList) : ?>
        <ul class="nav nav-pills">
            <?php if ($this->showPerPage && $this->paginationCount && count($this->perPageRanges) > 1) : ?>
                <li class="dropdown <?php if ($this->localization()->isCurrentLanguageLtr()) : ?>pull-right<?php else: ?>pull-left<?php endif; ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo $this->translate('Per page') ?> - <?php echo $this->per_page ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach ($this->perPageRanges as $perPage) : ?>
                            <li <?php if ($this->per_page == $perPage) : ?>class="disabled"<?php endif; ?>>
                                <a href="<?php echo $this->url('application', array_merge($this->baseUrlParams, array('per_page' => $perPage)), array('query' => $this->filterParams)) ?>"><?php echo $perPage ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>
            <?php endif; ?>

            <?php if ($this->orderList) : ?>
                <li class="dropdown <?php if ($this->localization()->isCurrentLanguageLtr()) : ?>pull-right<?php else: ?>pull-left<?php endif; ?>">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <?php echo $this->translate('Order') ?><?php if (!empty($this->orderList[$this->order_by])) : ?> - <?php echo $this->translate($this->orderList[$this->order_by]) ?><?php endif; ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <?php foreach ($this->orderList as $order => $orderTitle) : ?>
                            <li <?php if ($this->order_by == $order) : ?>class="disabled"<?php endif; ?>>
                                <a href="<?php echo $this->url('application', array_merge($this->baseUrlParams, array('order_by' => $order))) ?>">
                                    <?php echo $orderTitle ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                        <li class="divider"></li>
                        <li <?php if ($this->order_type == 'asc') : ?>class="disabled"<?php endif; ?>>
                            <a href="<?php echo $this->url('application', array_merge($this->baseUrlParams, array('order_type' => 'asc'))) ?>">
                                <?php echo $this->translate('Ascending') ?>
                            </a>
                        </li>
                        <li <?php if ($this->order_type == 'desc') : ?>class="disabled"<?php endif; ?>>
                            <a href="<?php echo $this->url('application', array_merge($this->baseUrlParams, array('order_type' => 'desc'))) ?>">
                                <?php echo $this->translate('Descending') ?>
                            </a>
                        </li>
                    </ul>
                </li>
            <?php endif; ?>
        </ul>
    <?php endif; ?>

    <div class="row">
        <?php foreach ($paginator as $data) : ?>
            <?php echo $this->partial($this->patrial, array(
                'data' => $data
            )) ?>
        <?php endforeach; ?>
    </div>

    <?php if ($this->paginationCount) : ?>
        <!-- pagination -->
        <?php
            echo $this->paginationControl($this->paginator, 'Sliding', 'partial/slide-paginator', array(
                'route' => 'application',
                'params' => array_merge($this->baseUrlParams, array(
                    'controller' => $this->controller, 
                    'action' => $this->action
                )),
            ))
        ?>
    <?php endif; ?>
</div>

<?php if ($this->ajax) : ?>
    <script type="text/javascript">
        // listen for all clicks
        $('#<?php echo $this->escapeJs($this->ajax_wrapper) ?>').find('.data-list .dropdown-menu a, .data-list ul.pagination a').bind('click', function(e){
            e.preventDefault();
            ajaxQuery('<?php echo $this->escapeJs($this->ajax_wrapper) ?>', $(this).attr('href')<?php if ($this->ajax_callback) : ?>, <?php echo $this->ajax_callback ?><?php endif; ?>);
        });
    </script>
<?php endif; ?>