<?php
    use Application\Form\CustomFormBuilder;
?>

<!-- include notifications -->
<?php if (!isset($this->notifications) || $this->notifications === true): ?>
    <?php echo $this->partial('partial/notification') ?>
<?php endif; ?>
<?php
    $this->declareVars('formOptions');

    // fill a form options
    $this->formOptions = array(
        'controller' => $this->controller,
        'action' => (!empty($this->action) ? $this->action : 'index')
    );

    // add extra form options
    if (!empty($this->params) && is_array($this->params)) {
        $this->formOptions = array_merge($this->formOptions, $this->params);
    }

    // init vars
    $this->declareVars('category', 'formCategories', 'openCategories', 'initCalendar', 'initWysiwyg', 'filePreview');

    $this->formCategories = new ArrayObject();
    $this->openCategories = new ArrayObject();
    $this->initCalendar = false;
    $this->initWysiwyg = false;
?>

<?php
    // group the form elements by categories
    $this->form->setAttribute('action', $this->url('administration', $this->formOptions, array('query' => !empty($this->queries) && is_array($this->queries) ? $this->queries : null)));
    $this->form->prepare();

    // process the form elements
    foreach ($this->form as $element) {
        // get an elements category
        $this->category = null != $element->getOption('category')
            ? $element->getOption('category')
            : false;

        // render the element
        $renderedElement = $this->formRow($element);

        // get the element's description
        if (null != ($elementDescription = $element->getOption('description'))) {
            $renderedElement .= '<p class="help-block">' . $elementDescription . '</p>';
        }

        // get element type
        if (null !== ($elementType = $form->getElementType($element->getName()))) {
            switch ($elementType) {
                case CustomFormBuilder::FIELD_IMAGE :
                case CustomFormBuilder::FIELD_FILE  :
                    // generate an image preview area
                    if (!empty($element->getOption('extra_options')['preview'])
                                && !empty($element->getOption('extra_options')['file_url'])) {

                        $this->filePreview = $elementType == CustomFormBuilder::FIELD_IMAGE
                            ? 'partial/_form-image-preview'
                            : 'partial/_form-file-preview';

                        $renderedElement .= $this->partial($this->filePreview, array(
                            'name' => $element->getName(),
                            'file_url' => $element->getOption('extra_options')['file_url'],
                            'delete_option' => !empty($element->getOption('extra_options')['delete_option'])
                                ? true
                                : false
                        ));
                    }
                    break;
                case CustomFormBuilder::FIELD_DATE :
                case CustomFormBuilder::FIELD_DATE_UNIXTIME :
                    $this->initCalendar = true;
                    break;
                case CustomFormBuilder::FIELD_HTML_AREA :
                case CustomFormBuilder::FIELD_NOTIFICATION_MESSAGE :
                    $this->initWysiwyg = true;
                    break;
            }            
        }

        // put the rendered element into categories array
        isset($this->formCategories[$this->category])
            ? $this->formCategories[$this->category] .= $renderedElement
            : $this->formCategories[$this->category]  = $renderedElement;

        // the element has a validation error and element's category should be opened
        if ($element->getMessages() &&
                    !in_array($this->category, (array) $this->openCategories)) {

            $this->openCategories[] = $this->category;
        }
    }
?>

<!-- render the form -->
<?php
    echo $this->form()->openTag($this->form);
    echo $this->partial('partial/accordion', array(
        'name' => 'settings-accordion',
        'items' => $this->formCategories,
        'openCategories' => $this->openCategories,
        'categoriesAlwaysOpened' => $this->categoriesAlwaysOpened
    ));
    echo $this->form()->closeTag();
?>

<?php if ($this->initWysiwyg): ?>
    <?php echo $this->partial('partial/_init-wysiwyg', array(
        'mode' => !empty($this->wysiwygMode) ? $this->wysiwygMode : null,
    ));?>
<?php endif; ?>

<?php if ($this->initCalendar): ?>
    <?php echo $this->partial('partial/_init-calendar') ?>
<?php endif; ?>