<div class="modal fade" id="<?php echo $this->escapeHtmlAttr($this->popup_id) ?>">
    <div class="modal-dialog <?php if($this->large): ?>modal-lg<?php endif ?>" <?php if($this->width): ?>style="width:<?php echo (int) $this->width ?>px;"<?php endif ?>>
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate($this->title) ?></h4>
            </div>
            <div class="modal-body" <?php if($this->height): ?>style="height:<?php echo (int) $this->height ?>px;"<?php endif ?>>
                <?php echo $this->body ?>
            </div>
            <?php if(!$this->hide_footer): ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
                    <?php echo $this->footer ?>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>