<?php
    $this->declareVars('queries', 'defaultRoute');

    if(!isset($this->params)) {
        $this->params = [];
    }

    $this->queries = !empty($this->queries) && is_array($this->queries) ? $this->queries : [];
    $this->defaultRoute = !empty($this->route) ? $this->route : 'application/page';
?>

<?php if ($this->pageCount > 1): ?>
    <ul class="pagination">
        <li <?php if (!isset($this->previous)): ?>class="disabled"<?php endif ?>>
            <?php if (isset($this->previous)): ?>
                <?php if (!$this->paginator_page_query): ?>
                    <a href="<?php echo $this->url($this->defaultRoute, ['page' => $this->previous] + $this->params, ['force_canonical' => true, 'query' => $this->queries, 'fragment' => $this->url_fragment]) ?>">&lt;</a>
                <?php else: ?>
                    <a href="<?php echo $this->url($this->defaultRoute, $this->params, ['force_canonical' => true, 'query' => [$this->paginator_page_query => $this->previous] + $this->queries, 'fragment' => $this->url_fragment]) ?>">&lt;</a>
                <?php endif ?>
            <?php else: ?>
                <span>&lt;</span>
            <?php endif ?>
        </li>

        <?php foreach ($this->pagesInRange as $page): ?>
            <li <?php if ($page == $this->current): ?>class="active"<?php endif; ?>>
                <?php if ($page != $this->current): ?>
                    <?php if (!$this->paginator_page_query): ?>
                        <a href="<?php echo $this->url($this->defaultRoute, ['page' => $page] + $this->params, ['force_canonical' => true, 'query' => $this->queries, 'fragment' => $this->url_fragment]) ?>">
                            <?php echo $page ?>
                        </a>
                    <?php else: ?>
                        <a href="<?php echo $this->url($this->defaultRoute, $this->params, ['force_canonical' => true, 'query' => [$this->paginator_page_query => $page] + $this->queries, 'fragment' => $this->url_fragment]) ?>">
                            <?php echo $page ?>
                        </a>
                    <?php endif ?>
                <?php else: ?>
                    <span><?php echo $page ?></span>
                <?php endif; ?>
            </li>
        <?php endforeach ?>

        <li <?php if (!isset($this->next)): ?>class="disabled"<?php endif ?>>
            <?php if (isset($this->next)): ?>
                <?php if (!$this->paginator_page_query): ?>
                    <a href="<?php echo $this->url($this->defaultRoute, ['page' => $this->next] + $this->params, ['force_canonical' => true, 'query' => $this->queries, 'fragment' => $this->url_fragment]) ?>">&gt;</a>
                <?php else: ?>
                    <a href="<?php echo $this->url($this->defaultRoute, ['page' => $this->next] + $this->params, ['force_canonical' => true, 'query' => [$this->paginator_page_query => $this->next] + $this->queries, 'fragment' => $this->url_fragment]) ?>">&gt;</a>
                <?php endif ?>
            <?php else: ?>
                <span>&gt;</span>
            <?php endif ?>
        </li>
    </ul>
<?php endif ?>