<div class="table-responsive">
    <table class="table table-hover table-striped">
        <?php if (!empty($this->headers)) : ?>
            <thead>
                <tr>
                    <?php foreach ($this->headers as $header) : ?>
                        <th><?php echo $header ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
        <?php endif; ?>
            <tbody>
                <?php foreach ($this->list as $items) : ?>
                    <tr>
                        <?php foreach ($items as $item) : ?>
                            <td><?php echo $item ?></td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
    </table>
</div>