<?php if (count($this->list)): ?>    
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <?php if (!empty($this->headers)): ?>
                <thead>
                    <tr>
                        <?php foreach ($this->headers as $header): ?>
                            <th><?php echo $this->translate($header) ?></th>
                        <?php endforeach ?>
                    </tr>
                </thead>
            <?php endif ?>
                <tbody>
                    <?php foreach ($this->list as $items): ?>
                        <tr>
                            <?php foreach ($items as $itemName => $itemValue) : ?>
                                <?php if (!empty($this->skipped_fields) && in_array($itemName, $this->skipped_fields)):  ?>
                                    <?php continue ?>
                                <?php endif ?>
                                <td>
                                    <?php if (!empty($this->helpers[$itemName])) : ?>
                                        <?php if (!empty($this->helpers_set_array) && array_key_exists($itemName, $this->helpers_set_array) ): ?>
                                             <?php echo $this->{$this->helpers[$itemName]}($items) ?>
                                        <?php else: ?>
                                             <?php echo $this->{$this->helpers[$itemName]}($itemValue) ?>
                                        <?php endif ?>                                       
                                    <?php else: ?>
                                        <?php echo $this->escapeHtml($itemValue) ?>
                                    <?php endif ?>
                                </td>
                            <?php endforeach ?>
                        </tr>
                    <?php endforeach ?>
                </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="alert alert-warning">
        <?php echo $this->translate('Nothing found') ?>
    </div>
<?php endif ?>
