<div class="table-responsive">
    <table class="table table-hover table-striped">
        <?php if (!empty($this->headers)) : ?>
            <thead>
                <tr>
                    <?php foreach ($this->headers as $header) : ?>
                        <th><?php echo $this->translate($header) ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
        <?php endif; ?>
            <tbody>
                <?php foreach ($this->list as $items) : ?>
                    <tr>
                        <?php foreach ($items as $itemName => $itemValue) : ?>
                            <td>
                                <?php if (!empty($this->helpers[$itemName])) : ?>
                                    <?php echo $this->{$this->helpers[$itemName]}($itemValue) ?>
                                <?php else: ?>
                                    <?php echo $this->escapeHtml($itemValue) ?>
                                <?php endif; ?>
                            </td>
                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
            </tbody>
    </table>
</div>