<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Users\Test\UsersBootstrap'                  => __DIR__ . '/test/Bootstrap.php',
  'Users\Test\Controller\LogoutControllerTest' => __DIR__ . '/test/Users/src/Users/Controller/LogoutControllerTest.php',
  'Users\Test\Controller\LoginControllerTest'  => __DIR__ . '/test/Users/src/Users/Controller/LoginControllerTest.php',
  'Users\Test\Service\ServiceTest'             => __DIR__ . '/test/Users/src/Users/Service/ServiceTest.php',
  'Users\Module'                               => __DIR__ . '/Module.php',
  'Users\Form\Login'                           => __DIR__ . '/src/Users/Form/Login.php',
  'Users\Controller\LogoutController'          => __DIR__ . '/src/Users/Controller/LogoutController.php',
  'Users\Controller\BaseController'            => __DIR__ . '/src/Users/Controller/BaseController.php',
  'Users\Controller\LoginController'           => __DIR__ . '/src/Users/Controller/LoginController.php',
  'Users\Event\Event'                          => __DIR__ . '/src/Users/Event/Event.php',
  'Users\Service\Service'                      => __DIR__ . '/src/Users/Service/Service.php',
  'Users\Model\XmlRpc'                         => __DIR__ . '/src/Users/Model/XmlRpc.php',
  'Users\Model\Base'                           => __DIR__ . '/src/Users/Model/Base.php',
  'Users\XmlRpc\Handler'                       => __DIR__ . '/src/Users/XmlRpc/Handler.php',
);
