<?php $this->layoutHeadScript()->appendFile($this->layoutAsset('payment.js', 'js', 'payment')) ?>
<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('payment.css', 'css', 'payment')) ?>

<?php if (!$this->localization()->isCurrentLanguageLtr()): ?>
    <?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('payment.rtl.css', 'css', 'payment')) ?>
<?php endif; ?>

<?php $this->inlineScript()->captureStart() ?>
    var payment = new Payment();
    payment.setServerUrl('<?php echo $this->url(null, array('controller' => 'payments')) ?>');
<?php $this->inlineScript()->captureEnd() ?>