<div class="row" id="shopping-cart" style="float: right">
    <div class="span2" style="float:right; margin-left: 50px;">
        <h5><b><?php echo $this->translate('Shopping cart') ?></b></h5>
        <?php if ($this->shoppingCart()->getItemsCount()) : ?>
            <a href="<?php echo $this->url('application', array('controller' => 'payment', 'action' => 'shopping-cart')) ?>">
                <?php echo sprintf($this->translate('Shopping cart info'), $this->shoppingCart()->getItemsCount(), $this->processCost($this->shoppingCart()->getItemsAmount())) ?></php>
            </a>
        <?php else: ?>
            <?php echo $this->translate('Shopping cart is empty') ?>
        <?php endif; ?>
    </div>
    <?php if ($this->exchangeRates()) : ?>
        <div class="span2" style="float:right">
            <h5><b><?php echo $this->translate('Currency') ?></b></h5>
            <?php foreach ($this->exchangeRates() as $currency => $rate) : ?>
                <a rel="nofollow" href="#"><?php echo $this->escapeHtml($currency) ?></a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>