<?php $this->declareVars('exchangeRates', 'exchangeRatesCount', 'activeShoppingCartCurrency', 'i') ?>
<?php $this->exchangeRates = $this->currency()->getExchangeRates(true) ?>
<?php $this->exchangeRatesCount = count($this->exchangeRates) ?>
<?php $this->activeShoppingCartCurrency = $this->currency()->getActiveShoppingCartCurrency() ?>

<div class="row" id="shopping-cart-wrapper">
    <div class="span2" id="shopping-cart-info">
        <h5><b><?php echo $this->translate('Shopping cart') ?></b><?php if ($this->shoppingCart()->getItemsCount()) : ?> - <?php echo sprintf($this->translate('Shopping cart info'), $this->shoppingCart()->getItemsCount(), $this->processCost($this->shoppingCart()->getItemsDiscountedAmount(), true)) ?><?php if ($this->shoppingCart()->getCurrentDiscount()) : ?> - <?php echo $this->translate('discount') ?>: <?php echo $this->escapeHtml($this->shoppingCart()->getCurrentDiscount()) ?>%<?php endif; ?><?php endif; ?></h5>
        <?php if ($this->shoppingCart()->getItemsCount()) : ?>
            <a href="<?php echo $this->url('application', array('controller' => 'payments', 'action' => 'shopping-cart')) ?>">
                <?php echo $this->translate('View the shopping cart') ?>
            </a> |
            <a rel="nofollow" href="javascript:void(0)" onclick="payment.cleanShoppingCart(<?php echo $this->currentRoute()->getController() == 'payments' && (in_array($this->currentRoute()->getAction(), array('shopping-cart', 'checkout'))) ? 'true' : 'false' ?>)">
                <?php echo $this->translate('Clean the shopping cart') ?>
            </a>
        <?php else: ?>
            <?php echo $this->translate('Shopping cart is empty') ?>
        <?php endif; ?>
    </div>
    <?php if ($this->exchangeRatesCount) : ?>
        <div class="span2" id="shopping-cart-currencies">
            <h5><b><?php echo $this->translate('Currency') ?></b></h5>
            <?php foreach ($this->exchangeRates as $currency) : ?>
                <?php $this->i++ ?>
                
                <?php if ($currency['code'] == $this->activeShoppingCartCurrency) : ?>
                    <span><?php echo $this->escapeHtml($currency['code']) ?></span>
                <?php else: ?>
                    <a rel="nofollow" href="javascript:void(0)" onclick="payment.changeCurrency('<?php echo $this->escapeJs($currency['code']) ?>')"><?php echo $this->escapeHtml($currency['code']) ?></a>
                <?php endif; ?>

                <?php if ($this->i < $this->exchangeRatesCount) : ?>
                |
                <?php endif; ?>

            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <div class="clearfix"></div>
</div>
<div class="clearfix" id="shopping-cart-clearfix"></div>