<!-- include needed js and css files -->
<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('administration-layout-2-columns-l66-r33.css', 'css', 'page')) ?>

<?php if (!$this->localization()->isCurrentLanguageLtr()): ?>
    <?php $this->layoutHeadLink()->
            appendStylesheet($this->layoutAsset('administration-layout-2-columns-l66-r33.rtl.css', 'css', 'page')) ?>
<?php endif ?>

<?php echo $this->layoutHeadLink() ?>

<table id="manage-widgets">
    <tbody>
        <tr>
            <td class="left-widgets-column">
                <ul class="connected-sortable default-widget-column" position="content-left">
                    <?php if (!empty($this->widgets_connections[$this->page_info['id']]['content-left'])): ?>
                        <?php foreach($this->widgets_connections[$this->page_info['id']]['content-left'] as $widget): ?>
                            <?php if (!$widget['widget_system']): ?>
                                <li class="ui-state-default" widget-connection="<?php echo $this->escapeHtmlAttr($widget['widget_connection_id']) ?>">
                                    <?php echo $this->partial('page/administration-partial/_widget-actions', []) ?>
                                    <?php echo $this->translate($widget['widget_description']) ?>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </ul>
            </td>
            <td class="right-widgets-column">
                <ul class="connected-sortable default-widget-column" position="content-right">
                    <?php if (!empty($this->widgets_connections[$this->page_info['id']]['content-right'])): ?>
                        <?php foreach($this->widgets_connections[$this->page_info['id']]['content-right'] as $widget): ?>
                            <?php if (!$widget['widget_system']): ?>
                                <li class="ui-state-default" widget-connection="<?php echo $this->escapeHtmlAttr($widget['widget_connection_id']) ?>">
                                    <?php echo $this->partial('page/administration-partial/_widget-actions', []) ?>
                                    <?php echo $this->translate($widget['widget_description']) ?>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </ul>
            </td>
        </tr>
    </tbody>
</table>