<?php $this->layoutHeadLink()->appendStylesheet($this->layoutAsset('administration-layout-1-column.css', 'css', 'page')) ?>
<?php echo $this->layoutHeadLink() ?>

<table id="manage-widgets">
    <tbody>
        <tr>
            <td>
                <ul class="connected-sortable default-widget-column" position="content-middle">
                    <?php if (!empty($this->widgets_connections[$this->page_info['id']]['content-middle'])): ?>
                        <?php foreach($this->widgets_connections[$this->page_info['id']]['content-middle'] as $widget): ?>
                            <?php if (!$widget['widget_system']): ?>
                                <li class="ui-state-default" widget-connection="<?php echo $this->escapeHtmlAttr($widget['widget_connection_id']) ?>">
                                    <?php echo $this->partial('page/administration-partial/_widget-actions', [
                                        'widget' => $widget,
                                        'allow_delete' => $this->allow_delete,
                                        'allow_view_dependents' => $this->allow_view_dependents,
                                        'allow_edit_settings' => $this->allow_edit_settings
                                    ]) ?>
                                    <span class="sortable-handler"><?php echo $this->pageWidgetTitle($widget) ?></span>
                                </li>
                            <?php endif ?>
                        <?php endforeach ?>
                    <?php endif ?>
                </ul>
            </td>
        </tr>
    </tbody>
</table>