<?php $this->declareVars('subPageTitle', 'parentSubPageTitle') ?>
<?php $this->parentSubPageTitle = $this->translate('Browse allowed ACL resources') ?>
<?php $this->subPageTitle = $this->translate($this->resourceSettings['resource_description']) ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentSubPageTitle) ?>
<?php $this->headTitle($this->user['nick_name']) ?>
<?php $this->headTitle($this->translate('List of users')) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of users'),
            'controller' => 'users-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_acl_resources' => [
            'name' => $this->user['nick_name'] . ' - ' . $this->parentSubPageTitle,
            'controller' => 'users-administration',
            'action' => 'browse-acl-resources',
            'check_acl' => true,
            'params' => [
                'slug' => $this->user['user_id']
            ]
        ],
        'acl_resource_settings' => [
            'name' => $this->subPageTitle,
            'controller' => 'users-administration',
            'action' => 'acl-resource-settings',
            'check_acl' => true,
            'slug' => $this->user['user_id']
        ]
    ]
]) ?>

<!-- render a form -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('General info'),
    'body' => $this->partial('partial/form', ['form' => $this->aclResourceSettingsForm])
]) ?>