<?php use User\Model\UserBase as UserBaseModel; ?>

<?php $this->declareVars('extraActions', 'subPageTitle', 'parentSubPageTitle') ?>
<?php $this->parentSubPageTitle = $this->translate('Browse allowed ACL resources') ?>
<?php $this->subPageTitle = $this->translate($this->resource_settings['resource_description']) ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentSubPageTitle) ?>
<?php $this->headTitle($this->user['nick_name']) ?>
<?php $this->headTitle($this->translate('List of users')) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of users'),
            'controller' => 'users-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_acl_resources' => [
            'name' => $this->user['nick_name'] . ' - ' . $this->parentSubPageTitle,
            'controller' => 'users-administration',
            'action' => 'browse-acl-resources',
            'check_acl' => true,
            'params' => [
                'slug' => $this->user['user_id']
            ]
        ],
        'acl_resource_settings' => [
            'name' => $this->subPageTitle,
            'controller' => 'users-administration',
            'action' => 'acl-resource-settings',
            'check_acl' => true,
            'slug' => $this->user['user_id']
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'users-administration',
        'action' => 'edit-user',
        'params' => [
          'slug' => $this->user['user_id']
        ],
        'name' => $this->translate('Edit the user'),
        'check_acl' => true
    ],
    [
        'hide_action' =>  UserBaseModel::DEFAULT_USER_ID == $this->user['user_id'],
        'controller' => 'users-administration',
        'action' => 'edit-role',
        'params' => [
            'slug' => $this->user['user_id']
        ],
        'name' => $this->translate('Edit the user\'s role'),
        'check_acl' => true
    ],
    [
        'hide_action' => UserBaseModel::DEFAULT_USER_ID == $this->user['user_id'],
        'controller' => 'users-administration',
        'action' => 'delete',
        'name' => $this->translate('Delete the user'),
        'check_acl' => true,
        'confirm' => $this->translate('User will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'users' : [{$this->user['user_id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'users-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => UserBaseModel::STATUS_APPROVED == $this->user['status'],
        'controller' => 'users-administration',
        'action' => 'approve',
        'name' => $this->translate('Approve the user'),
        'check_acl' => true,
        'confirm' => $this->translate('User will be approved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'users' : [{$this->user['user_id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'users-administration', 'action' => 'acl-resource-settings', 'slug' => $this->resource_settings['connection']], ['query' => ['user' => $this->user['user_id']], 'force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => UserBaseModel::STATUS_APPROVED != $this->user['status'],
        'controller' => 'users-administration',
        'action' => 'disapprove',
        'name' => $this->translate('Disapprove the user'),
        'check_acl' => true,
        'confirm' => $this->translate('User will be disapproved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'csrf' : '{$this->csrf_token}', 'users' : [{$this->user['user_id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'users-administration', 'action' => 'acl-resource-settings', 'slug' => $this->resource_settings['connection']], ['query' => ['user' => $this->user['user_id']], 'force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'users-administration',
        'action' => 'add-user',
        'name' => $this->translate('Add a user'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
   <?php if (!$this->extraActions): ?> 
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('General info'),
                'body' => $this->partial('partial/form', ['form' => $this->acl_form])
            ]) ?>
        </div>
    <?php else: ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('General info'),
                'body' => $this->partial('partial/form', ['form' => $this->acl_form])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php endif ?>
</div>
