<?php use User\Model\UserBase as UserBaseModel; ?>

<?php $this->declareVars('extraActions', 'subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('Browse allowed ACL resources')  ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->user['nick_name']) ?>
<?php $this->headTitle($this->translate('List of users')) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of users'),
            'controller' => 'users-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_acl_resources' => [
            'name' => $this->user['nick_name'] . ' - ' . $this->subPageTitle,
            'controller' => 'users-administration',
            'action' => 'browse-acl-resources',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'users-administration',
    'action' => 'browse-acl-resources',
    'slug' => $this->slug,
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('Description')
        ],
        [
            'title' => $this->translate('Module')
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'connection'  
    ],
    'helpers' => [
        'description' => 'translate',
        'module' => 'translate'
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
        ],
        'multiple_actions' => [
        ],
        'single_actions' => [
            [
                'name' => $this->translate('Resource\'s settings'),
                'controller' => 'users-administration',
                'action' => 'acl-resource-settings',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/setting_action.png', 'image'),
                'param' => 'connection',
                'queries' => [
                    'user' => $user['user_id']
                ]
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'acl-resources'
    ],
    'actions_extra_check' => [
        'single_actions' => [
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'users-administration',
        'action' => 'edit-user',
        'params' => [
            'slug' => $this->user['user_id']
        ],
        'name' => $this->translate('Edit the user'),
        'check_acl' => true
    ],
    [
        'hide_action' =>  UserBaseModel::DEFAULT_USER_ID == $this->user['user_id'],
        'controller' => 'users-administration',
        'action' => 'edit-role',
        'params' => [
            'slug' => $this->user['user_id']
        ],
        'name' => $this->translate('Edit the user\'s role'),
        'check_acl' => true
    ],
    [
        'hide_action' => UserBaseModel::DEFAULT_USER_ID == $this->user['user_id'],
        'controller' => 'users-administration',
        'action' => 'delete',
        'name' => $this->translate('Delete the user'),
        'check_acl' => true,
        'confirm' => $this->translate('User will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'users' : [{$this->user['user_id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'users-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => UserBaseModel::STATUS_APPROVED == $this->user['status'],
        'controller' => 'users-administration',
        'action' => 'approve',
        'name' => $this->translate('Approve the user'),
        'check_acl' => true,
        'confirm' => $this->translate('User will be approved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'users' : [{$this->user['user_id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'users-administration', 'action' => 'browse-acl-resources', 'slug' => $this->user['user_id']], ['force_canonical' => true])}'}) }"
    ],
    [
        'hide_action' => UserBaseModel::STATUS_APPROVED != $this->user['status'],
        'controller' => 'users-administration',
        'action' => 'disapprove',
        'name' => $this->translate('Disapprove the user'),
        'check_acl' => true,
        'confirm' => $this->translate('User will be disapproved. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'users' : [{$this->user['user_id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'users-administration', 'action' => 'browse-acl-resources', 'slug' => $this->user['user_id']], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'users-administration',
        'action' => 'add-user',
        'name' => $this->translate('Add a user'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
   <?php if (!$this->extraActions): ?> 
        <div class="col-md-12">
            <!-- render a data grid -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Resources'),
                'body' => $this->content
            ]) ?>
        </div>
    <?php else: ?>
        <div class="col-md-8">
            <!-- render a data grid -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Resources'),
                'body' => $this->content
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php endif ?>
</div>