<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('Browse allowed ACL resources')  ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->user['nick_name']) ?>
<?php $this->headTitle($this->translate('List of users')) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->translate('List of users'),
            'controller' => 'users-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'browse_acl_resources' => [
            'name' => $this->user['nick_name'] . ' - ' . $this->subPageTitle,
            'controller' => 'users-administration',
            'action' => 'browse-acl-resources',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'users-administration',
    'action' => 'browse-acl-resources',
    'slug' => $this->slug,
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        0 => [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        1 => [
            'title' => $this->translate('Description')
        ],
        2 => [
            'title' => $this->translate('Module')
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'connection'  
    ],
    'helpers' => [
        'description' => 'translate',
        'module' => 'translate'
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
        ],
        'multiple_actions' => [
        ],
        'single_actions' => [
            0 => [
                'name' => $this->translate('Resource\'s settings'),
                'controller' => 'users-administration',
                'action' => 'acl-resource-settings',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/setting_action.png', 'image'),
                'param' => 'connection',
                'queries' => [
                    'user' => $user['user_id']
                ]
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'acl-resources'
    ],
    'actions_extra_check' => [
        'single_actions' => [
            'resource-settings' => [
                0 => [
                    'param' => 'conection',
                    'condition' =>  'return (int) "__value__" > 0;'
                ]
            ]
        ]
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Resources'),
    'body' => $this->content
]) ?>