<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Browse allowed ACL resources')  ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->user['nick_name']) ?>
<?php $this->headTitle($this->translate('List of users')) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->translate('List of users'),
            'controller' => 'users-administration',
            'action' => 'list',
            'check_acl' => true
        ),
        'browse_acl_resources' => array(
            'name' => $this->user['nick_name'] . ' - ' . $this->subPageTitle,
            'controller' => 'users-administration',
            'action' => 'browse-acl-resources',
            'check_acl' => true
        )
    )
)) ?>

<!-- render a data grid -->
<?php echo $this->partial('partial/data-grid', array(
    'controller' => 'users-administration',
    'action' => 'browse-acl-resources',
    'slug' => $this->slug,
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => array(
        0 => array(
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ),
        1 => array(
            'title' => $this->translate('Description')
        ),
        2 => array(
            'title' => $this->translate('Module')
        )
    ),
    'paginator' => $this->paginator,
    'skipped_fields' => array(
        'connection'  
    ),
    'helpers' => array(
        'description' => 'translate',
        'module' => 'translate'
    ),
    'helpers_options' => array(
    ),
    'actions' => array(
        'regular_actions' => array(
        ),
        'multiple_actions' => array(
        ),
        'single_actions' => array(
            0 => array(
                'name' => $this->translate('Resource\'s settings'),
                'controller' => 'users-administration',
                'action' => 'acl-resource-settings',
                'check_acl' => true,
                'image' => $this->asset('icon/setting_action.png', 'image'),
                'param' => 'connection',
                'queries' => array(
                    'user' => $user['user_id']
                )
            ),
        )
    ),
    'actions_options' => array(
        'action_identity' => 'id',
        'form_name' => 'acl-resources'
    ),
    'actions_extra_check' => array(
        'single_actions' => array(
            'resource-settings' => array(
                0 => array(
                    'param' => 'conection',
                    'condition' =>  'return (int) "__value__" > 0;'
                )
            )
        )
    )
)) ?>