<?php $this->declareVars('subPageTitle') ?>
<?php $this->subPageTitle = $this->translate('Edit the user\'s role') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->user['nick_name']) ?>
<?php $this->headTitle($this->translate('List of users')) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('partial/tab', array(
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
)) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('partial/breadcrumb', array(
    'pages' => array(
        'list' => array(
            'name' => $this->translate('List of users'),
            'controller' => 'users-administration',
            'action' => 'list',
            'check_acl' => true
        ),
        'edit_role' => array(
            'name' => $this->user['nick_name'] . ' - ' . $this->subPageTitle,
            'controller' => 'users-administration',
            'action' => 'edit-role',
            'check_acl' => true
        )
    )
)) ?>

<!-- render a form -->
<?php echo $this->partial('partial/form', array(
    'form' => $this->roleForm,
    'controller' => 'users-administration',
    'action' => 'edit-role',
    'params' => array(
        'slug' => $this->user['user_id']
    )
)); ?>