<?php use Acl\Model\AclBase as AclBaseModel; ?>
<?php use User\Model\UserBase as UserBaseModel; ?>

<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of users') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('user/user-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'users-administration',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('NickName'),
            'order_name' => 'nickname'
        ],
        [
            'title' => $this->translate('Email'),
            'order_name' => 'email'
        ],
        [
            'title' => $this->translate('Status'),
            'order_name' => 'status'
        ],
        [
            'title' => $this->translate('Registered date'),
            'order_name' => 'registered'
        ],
        [
            'title' => $this->translate('Role')
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'role_id'  
    ],
    'helpers' => [
        'role' => 'translate',
        'status' => 'translate',
        'registered' => 'applicationDate'
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
            [
                'name' => $this->translate('Add a user'),
                'controller' => 'users-administration',
                'action' => 'add-user',
                'check_acl' => true
            ]
        ],
        'multiple_actions' => [
            [
                'name' => $this->translate('Approve selected'),
                'controller' => 'users-administration',
                'action' => 'approve',
                'check_acl' => true
            ],
            [
                'name' => $this->translate('Disapprove selected'),
                'controller' => 'users-administration',
                'action' => 'disapprove',
                'check_acl' => true
            ],
            [
                'name' => $this->translate('Delete selected'),
                'controller' => 'users-administration',
                'action' => 'delete',
                'check_acl' => true,
                'confirm' => $this->translate('Selected users will be deleted. Are you sure?')
            ]
        ],
        'single_actions' => [
            [
                'name' => $this->translate('Edit the user\'s role'),
                'controller' => 'users-administration',
                'action' => 'edit-role',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/role_action.png', 'image', 'user')
            ],
            [
                'name' => $this->translate('Browse allowed ACL resources'),
                'controller' => 'users-administration',
                'action' => 'browse-acl-resources',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/browse_action.png', 'image', 'acl')
            ],
            [
                'name' => $this->translate('Edit the user'),
                'controller' => 'users-administration',
                'action' => 'edit-user',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/edit_action.png', 'image')
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'users',
        'multiple_actions' => [
            'items_name' => 'users[]'
        ]
    ],
    'actions_extra_check' => [
        'multiple_actions' => [
            'system_user' => [
                'param' => 'id',
                'condition' =>  'return "__value__" == "' . UserBaseModel::DEFAULT_USER_ID . '" ? false : true;'
            ]
        ],
        'multiple_actions_message' => $this->translate('You cannot delete, approve or disapprove the default user default user'),
        'single_actions' => [
            'browse-acl-resources' => [
                [
                    'param' => 'role_id',
                    'condition' =>  'return "__value__" == "' . AclBaseModel::DEFAULT_ROLE_ADMIN . '" ? false : true;'
                ]
            ],
            'edit-role' => [
                [
                    'param' => 'id',
                    'condition' =>  'return "__value__" == "' . UserBaseModel::DEFAULT_USER_ID . '" ? false : true;'
                ]
            ]
        ]
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Users'),
    'body' => $this->content
]) ?>