<?php $this->placeholder('popupBody')->captureStart() ?>
    <?php if($this->resources): ?>
        <?php echo $this->partial('partial/table', array(
            'headers' => array(
                'Description'
            ),
            'list' => $this->resources,
            'helpers' => array(
                'description' => 'translate'
            )
        )) ?>
    <?php else: ?>
        <div class="alert alert-warning"><?php echo $this->translate('Nothing found') ?></div>
    <?php endif;?>
<?php $this->placeholder('popupBody')->captureEnd() ?>

<?php 
    echo $this->partial('partial/popup', array(
        'popup_id' => 'popup-acl-resources-window',
        'title' => 'Permitted actions',
        'body' => $this->placeholder('popupBody')
    )) 
?>