<div class="modal fade" id="popup-acl-resources-window">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('Permitted actions') ?></h4>
            </div>
            <div class="modal-body">
                <?php if($this->resources): ?>
                    <?php echo $this->partial('partial/table', array(
                        'headers' => array(
                            'Description'
                        ),
                        'list' => $this->resources,
                        'helpers' => array(
                            'description' => 'translate'
                        )
                    )) ?>
                <?php else: ?>
                    <div class="alert alert-warning"><?php echo $this->translate('Nothing found') ?></div>
                <?php endif;?>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Close') ?></button>
            </div>
        </div>
    </div>
</div>